### ISSUE TITLE
Unfired Clay Shears have 238 durability

### ISSUE THREAD

**Issue by al132mc** [codetaylor/pyrotech#100]
#### Issue Description

Unfired clay shears have 238 durability. They probably shouldn't be able to shear trees at all, and if they can they shouldn't have more durability than fired shears.

#### What Happens

See above

#### What You Expect to Happen

Unfired shears to have no durability...

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* CraftTweaker: 1.12-2-8.1.9
* Dropt: 1.12.2-1.15.1
* Pyrotech: 1.12.2-1.2.2
* Athenaeum: 1.12.2-1.17.2

**Comment by codetaylor** [comment]
![image](https://user-images.githubusercontent.com/1240716/60737075-4192a980-9f0e-11e9-91d7-90290210ae40.png)

lol... whyyy?

**Comment by codetaylor** [comment]
> They probably shouldn't be able to shear trees at all

Yeah, that was the original intent.

**Comment by codetaylor** [comment]
Thank you for the report!

This is fixed in 1.12.2-1.2.3 which should be out later today.
