### ISSUE TITLE
Iron ingots found in loot tables break progression

### ISSUE THREAD

**Issue by codetaylor** [codetaylor/pyrotech#102]
Players can find iron ingots in the wild and it will prematurely unlock entries in the guidebook.

From the Discord:
![image](https://user-images.githubusercontent.com/1240716/60740297-00a09200-9f1a-11e9-872b-429bbe7f61ba.png)

Edit: It will unlock advancements prematurely which then unlocks the guidebook entries as a result.

**Comment by AnotherVagabond** [comment]
How hard would it be to just change iron ingots to iron ore or even iron dust if they show up in any generated structures? If that could be set as a config, it would solve the problem, but I don't know if there's a way you can code it to catch all possible loot tables, or if it's even feasible to program it that way in the first place.

**Comment by DWX12** [comment]
Another issue are mobs, such as iron golems and zombies, that drop iron ingots.

**Comment by codetaylor** [comment]
@AnotherVagabond I like your idea of changing the iron ingots into iron ore. When I have time to look into this, I'll probably start by looking at how other mods modify loot tables, specifically the CraftTweaker loot table mods, to get an idea of how it's done. Once I know more, I'll see if it would be feasible to try and modify all loot tables.

**Comment by codetaylor** [comment]
Alternatively, ore chunks could drop instead: #106 

Configs galore ofc.

**Comment by codetaylor** [comment]
Pyrotech will now scan loot tables and replace any Iron Ingot with Iron Ore. I've also added a config flag to disable this feature. It will likely have undefined results when used with other mods that mess with loot tables using the same event, such as LootTweaker.

This will be available in `1.4.0`.
