### ISSUE TITLE
Server crash loop, null recipe key in active pile

### ISSUE THREAD

**Issue by Yldales** [codetaylor/pyrotech#103]
Hi,

#### Issue Description
A player was experimenting with igniters, and then the server crashed. After restarting it, whenever someone connects near the zone, the server crashes again instantly.

#### What Happens
(I'm still trying to figure this out with the player).
1. Place an Igniter.
2. Place a button behind the Igniter.
3. Push the button.

#### What You Expect to Happen
Not this ;-;

#### Script
No CraftTweaker script(s) used.

#### Crash Log
https://pastebin.com/raw/wA2v1yYm

#### Affected Versions
* Minecraft: 1.12.2
* Forge: 1.12.2-14.23.5.2838
* CraftTweaker: 4.1.19
* Dropt: 1.14.0
* Pyrotech: 1.2.2
* Athenaeum: 1.17.2

**Comment by codetaylor** [comment]
Thank you for the report!

From what I can tell, the provided crash is happening because the recipe key for an active pile is null when the game tries to serialize it, which should not ever happen. Active piles are created when a Pit Burn or Refractory Burn is first ignited.

I would like to figure out under which conditions this was able to happen.

1. Have you added any Pit Burn / Refractory Burn recipes using CraftTweaker?
2. Is Pyrotech using a default or close to default configuration? 
    * If not, off the top of your head, do you know what's been changed?

**Comment by Yldales** [comment]
1. Currently, there are no Crafttweaker scripts enabled. However, yesterday I tried the following script: https://pastebin.com/ncQvSMVq
2. This script has been deprecated in favor of the option pit_kiln.BASE_RECIPE_DURATION_MODIFIER (currently set to 0.5) in module.tech.Basic.cfg. Except for that, nothing has been changed in the configurations files.

Also, I've encountered another may-be related crash. Should I create another issue, or post it here ?

**Comment by codetaylor** [comment]
Please create another issue in case it isn't related and I can link it to this one if it is related.

**Comment by codetaylor** [comment]
Yeah, pretty sure the Pit Kiln stuff that you changed doesn't affect this; this is a Pit Burn issue, like lighting a log pile and covering it, or starting it with an igniter block - which is what I think happened here. I'm still not sure what would cause that value to be null under normal operating conditions.

**Comment by Yldales** [comment]
Okay, thanks for your quick answers. Is there anything I can test, do or provide to help ?

**Comment by codetaylor** [comment]
I think being able to inspect the full log around the time that this happened might shed some light on why it happened.

Is this crash continuing to happen or was it somehow resolved? If so, how did you resolve it?

**Comment by Yldales** [comment]
I've used an external map editor (mcEdit) to remove the igniters, refractory bricks, etc... in the area.

**Comment by codetaylor** [comment]
> A player was experimenting with igniters

I'll bet that this problem occurred due to #107, which has been fixed. I'm going to close this, but feel free to create another issue if this happens again after switching to the fixed version.
