### ISSUE TITLE
StackOverflowError: Exception while updating neighbours

### ISSUE THREAD

**Issue by Yldales** [codetaylor/pyrotech#107]
#### Issue Description
This issue about a crash when someone opens the door of a refractory burning structure. This structure has already been used before, without this problem.

#### What Happens
![pyrotech_issue_2](https://user-images.githubusercontent.com/50544935/60765173-5bf78f00-a096-11e9-9da8-10c1b9f55ef8.png)
1. The server crash when someone try to open the door visible on the screenshot.

#### What You Expect to Happen
No server crash.

#### Script
No CraftTweaker script(s) used.

#### Crash Log
https://pastebin.com/raw/P8B4H9Ce

#### Affected Versions
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2838
- CraftTweaker: 4.1.19
- Dropt: 1.14.0
- Pyrotech: 1.2.2
- Athenaeum: 1.17.2

Thanks in advance.

**Comment by codetaylor** [comment]
Thank you for the report, I will be investigating this and will report what I find.

**Comment by codetaylor** [comment]
Is this the setup that also caused #103 ?

**Comment by codetaylor** [comment]
I was able to reliably reproduce this by pressing the button on an igniter that is placed in the air like so:

![image](https://user-images.githubusercontent.com/1240716/60771086-68301c00-a097-11e9-86cf-acc55d0bd70d.png)

**Comment by Yldales** [comment]
> 
> 
> Is this the setup that also caused #103 ?

It's another setup.

**Comment by codetaylor** [comment]
I'll bet that this is the problem that caused the other issue, #103.

Thank you for the images you provided, they were very helpful.

I've fixed the problem, but any Stone Igniter or Refractory Igniter currently in the world will be inert after this update. They will need to be broken and replaced in order to function.

**Comment by Yldales** [comment]
Thanks you a lot.
