### ISSUE TITLE
Oredict suggestions

### ISSUE THREAD

**Issue by lynaevm** [codetaylor/pyrotech#108]
Here are a few existing oredicts from other popular mods that you might consider tieing into:

fuelCoke
blockFuelCoke
oreNetherCoal -- may already be a dense version as well, but don't have a mod installed that includes it

suspect and can't verify that something exists for glass shards, ash, stone rod, 

oh, and only one of your own twines is in the ore:twine group.

**Comment by codetaylor** [comment]
Thank you for the report!

I don't have time to go hunting for all the established oredict keys, so I really appreciate the oredict reports.

Twine oversight confirmed:
![image](https://user-images.githubusercontent.com/1240716/60996516-961c9700-a309-11e9-88bb-000483beea7d.png)
