### ISSUE TITLE
Dedicated server crash

### ISSUE THREAD

**Issue by Yoghurt4C** [codetaylor/pyrotech#11]
dedicated server went into a cyclic crash after an attempt to place a chopping block, here's what exactly happened:
-chopping block got placed by a player
-player tries to break chopping block
-it doesn't actually break
-player tries to rightclick on other blocks while using the hotbar slot where the chopping block originally was
-more "fake" chopping blocks get placed
- suddenly, the server says goodbye

log:
https://pastebin.com/DWmezjh6

* Forge: 2838
* Pyrotech: 1.0.0

**Comment by codetaylor** [comment]
Thanks for the report!

It looks like the server is trying to use a client only class: `org/lwjgl/util/vector/ReadableVector4f`.

**Comment by codetaylor** [comment]
Looks like it's my use of LWJGL's `Quaternion` here: https://github.com/codetaylor/pyrotech/blob/master/src/main/java/com/codetaylor/mc/pyrotech/interaction/api/Transform.java#L5

I'm going to have to use a different quaternion class.

**Comment by codetaylor** [comment]
Fixed in 1.12.2-1.0.1
