### ISSUE TITLE
Separate crafting tables from other basic tech in config

### ISSUE THREAD

**Issue by inkdear** [codetaylor/pyrotech#111]
I think it might be a fairly common desire to disable Pyrotech's worktables in favour of the vanilla one, while retaining the other stuff in the Basic Tech module. It wouldn't be that much of an issue to just leave it in and not use it, except that JEI still shows the worktable tabs/recipes, which feels kind of extraneous and fluffy if you're not actually using them. My apologies if there's a way to disable them that I haven't found! Thank you for reading!

**Comment by codetaylor** [comment]
Here is a script that will hide both worktables as well as the worktable category in JEI.

```
import mods.jei.JEI;

JEI.hide(<pyrotech:worktable>);
JEI.hide(<pyrotech:worktable_stone>);

JEI.hideCategory("pyrotech.worktable");
```

See also: https://crafttweaker.readthedocs.io/en/latest/#Mods/JEI/JEI/#remove

**Comment by inkdear** [comment]
Thank you! Didn't even know you could do that.

**Comment by codetaylor** [comment]
You're welcome :)
