### ISSUE TITLE
Contents of rock bag destroyed when you go into creative mode

### ISSUE THREAD

**Issue by codetaylor** [codetaylor/pyrotech#117]
![image](https://user-images.githubusercontent.com/1240716/61061028-5bba0500-a3b0-11e9-8d07-876a06a39b4a.png)

**Comment by duely** [comment]
Damn it, now I can't reproduce the exact steps. I know that this is a known issue with capabilities & creative mode. It might be limited to multiplayer servers? I'm not exactly sure. I know the Quark backpack suffered from this issue, and until I converted them to use NBT, the Roots 3 Staff and Pouch also suffered from the same problem.

**Comment by codetaylor** [comment]
@duely Ok, I see what you did with the Pouch: https://github.com/EpicSquid/Roots/blob/master/src/main/java/epicsquid/roots/handler/PouchHandler.java

You're just bypassing the capability system completely and operating directly on the stack's NBT.

I'd love to understand why this happens though and why bypassing the capability system is the solution.

**Comment by duely** [comment]
https://github.com/Vazkii/Quark/blob/master/src/main/java/vazkii/quark/oddities/item/ItemBackpack.java 

I know the most recent backpack is functioning properly and no longer suffers from a "creative mode randomly deletes your capabilities" issue.

**Comment by codetaylor** [comment]
![image](https://user-images.githubusercontent.com/1240716/61146707-8333cf00-a48f-11e9-81ae-68e658643032.png)

**Comment by codetaylor** [comment]
![image](https://user-images.githubusercontent.com/1240716/61146731-9181eb00-a48f-11e9-8335-a7261ae8d193.png)
