### ISSUE TITLE
Guidebook Unlocking Suggestions

### ISSUE THREAD

**Issue by lynaevm** [codetaylor/pyrotech#128]
Detailed feedback as requesting re: patchouli guidebook locks.

First a bit of a stream-of-consciousness feedback as I worked through the achievements.  Later, a much more coherent proposal.

*anvil appears on guidebook pages from the beginning (bone shards etc) but doesn't unlock for quite a while.  Could be confusing and frustrating.

*Ditto crude drying rack.  I know you can get dried grass from breaking grass, but when there is a recipe displayed better to just have it pre-unlocked.  Especially since its 2x2

*I think fiber torch should be visible from the beginning because people like to know they are set for torches asap.

*gating twine just seems weird.

*gating lump of clay behind crude pickaxe is illogical to me.

*I think the fact that you need to use a chopping block to make a worktable does NOT mean that you should need a chopping block to find out that the worktable exists -- players will want a crafting table asap or want to know why not.

*food-roasted -- since you already said in an early entry that campfires make delicious food, it seems weird to gate the rest of that concept.

*Hammer should be visible as soon as worktable is, since its required for it.  You want to be able to use something as soon as you make it.

*strange that I can see clay bucket entry an achievement before I can see clay shears.

*Currently, you read the directions for the refractory brick before you unlock the stone crucible or soaking tub.  I forget what unlocked them but it was too soon.

*Both flint and bone pick look like they are dependent on the anvil in jei: only the book gives you hints as to getting them as drops. May be fixed with JER.

*the organization of the achievement string is a bit confusing, since masonry bricks are dependent on the anvil but are attached to other branch.

*double check what unlocks the granite anvil entry in the book, the stone slab or the stone block.

*super weird to me that you craft stone bricks the vanilla way but then have to put it through two runs on the granite anvil to take them back APART into bricks.  Not actually relevant to this topic though lol.

*soaking section and 4 recipes unlock at masonry bricks but soaking pot entry itself (and paper) doesn't unlock until after "Adequate Appliances".

*Why does bow drill unlock behind masonry brick? Only requires sticks and string.

*Bellows and igniters shouldn't have to wait until you've made all 4 "adequate appliances" to be unlocked since you may well want to use them on the first one you make.... or use your knowledge of them to figure out how many bricks you need.

*No slaked lime entry in soaking section? or Quicklime mention somewhere? I found it under refractory brick, but since it has its own achievement before the refractory brick may want to split it off to its own entry so you can find it in the index.

*Bloomery unlocks "advanced hammers" many of which require ingots you can't make just yet but seems to imply that you immediately need -- may be good to clarify or delay to behind iron ingot?

*Mechanical mulcher -- why gated behind iron? seems to fit with the earlier cog machines like hopper

*Living Tar achievement looks like its achievable earlier (and well before the book entry for it unlocks) -- move it over by other post-nether goals?

*obsidian tools entry unlocks well after we've seen obsidian shards elsewhere (advanced hammers for example)

In general, I think you have too many locks and perhaps too many achievements as well.

I would suggest things unlock in larger chunks:

Group 1 -- from beginning of game -- all the 2x2 recipes or gathered components.

Group 2 --unlocked by worktable --  all early game crafts until the stone brick

Group 3 -- unlocked by stone brick -- all stone combustion machines, early cog machines, and soaking tub

Group 4 -- unlocked by refractory brick -- bloomery, all refractory machines and early metal stuff.

Group 5 -- unlocked by nether -- remaining nether-dependent machines.

**Comment by codetaylor** [comment]
Thank you very much for the awesome feedback! I will definitely make use of this data. :)

Linking to related #75
