### ISSUE TITLE
When an anvil is broken while hammering a bloom, it should place the bloom on the block below.

### ISSUE THREAD

**Issue by AnotherVagabond** [codetaylor/pyrotech#129]
If you break an anvil while hammering a bloom, the bloom drops as an item and is automatically picked up if you're close to it (which you almost certainly will be), causing damage. I think it would be better if, instead of dropping the bloom as an item, it automatically placed the bloom on the block that was below the anvil, only dropping the bloom as an item if there is no block below the anvil to place it on. This gives us a chance to pick it back up with some tongs instead of automatically picking it up and taking damage for doing so.

**Comment by codetaylor** [comment]
Having the bloom drop down isn't a bad idea.

Protip: If you have a pair of tongs in either your main hand or offhand, any bloom that you pick up will automatically go into the tongs.

**Comment by AnotherVagabond** [comment]
Oh, I didn't know about the off-hand tong thing, that's much more convenient. Thanks!

**Comment by codetaylor** [comment]
You're welcome :)

**Comment by DWX12** [comment]
I second the bloom landing on the ground after the anvil breaks idea. I died from a bloom going in my inventory after the anvil broke and I too did not know about the off hand tong interaction.
