### ISSUE TITLE
Crash on startup | ArrayIndexOutOfBoundsException: 0

### ISSUE THREAD

**Issue by HurtsAsHell** [codetaylor/pyrotech#133]
It Is a custom modpack and the first time I started the modpack everything went smoothly, now it doesn't start anymore

#### What Happens

Game crash on load and i haven't modified any recipes

#### Crash Log

https://pastebin.com/aG1e3SZL

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* CraftTweaker: 4.1.19
* Pyrotech: 1.2.7
* Athenaeum: 1.17.3

**Comment by HurtsAsHell** [comment]
I'm sorry, i have closed the issues for mistake

**Comment by codetaylor** [comment]
Thanks for the report!

Can you please provide links to the following config files found in `config/pyrotech`:
* `core.compat.Ore-Custom.json`
* `core.compat.Ore-Generated.json`

**Comment by codetaylor** [comment]
Also, have you removed any mods since the first load? Specifically any mods that have ores?

**Comment by codetaylor** [comment]
I believe I have fixed this issue in `1.2.8`. If it still crashes let me know. :)
