### ISSUE TITLE
Terracotta in Kiln

### ISSUE THREAD

**Issue by lynaevm** [codetaylor/pyrotech#134]
Clay block to terracotta should be added to the included default recipe list for all the kilns.  Perhaps color and glazed variations as well.

You might also consider adding more ways to recycle slag: I love the slag glass but perhaps you could stretch the idea of cement to include soaking a block of slag in (something) to make clay, since you use quite a bit of it in this pack.

**Comment by codetaylor** [comment]
Thanks! I split the slag half into a new thread #136

**Comment by DWX12** [comment]
I second the idea of getting clay back from terracotta shards and pieces instead of or in addition to just sand.

**Comment by codetaylor** [comment]
Both the hardened clay and glazed terracotta have been added to the kiln recipes in 1.4.0
