### ISSUE TITLE
Add config option to toggle the shovel requirement for collecting large wood chip piles

### ISSUE THREAD

**Issue by wormzjl** [codetaylor/pyrotech#137]
Breaking single wood chip on the ground works fine, but when it starts stacking nothing can be dropped.

**Comment by codetaylor** [comment]
Wood piles can only be collected with a shovel.

**Comment by wormzjl** [comment]
Hmmm this design is kinda weird and player can get confused due to inconsistency, might consider adding a config for that?

**Comment by AnotherVagabond** [comment]
I'll admit this caught me the first time too. I think the default should be either one or the other, to be honest: either one set can't be picked up with your hands, or all of it can be picked up with your hands. It doesn't really make sense why, for example, a bit of wood chips on the ground can be picked up by hand, but a bit of wood chips on top of another bit of wood chips can't.

**Comment by codetaylor** [comment]
Yeah, I plan to change it to allow all wood chips to be collected with your hands by default, with a config to restrict it to the shovel. It will match the behavior of the wood chips on the ground as well as the chips on the chopping block.

**Comment by codetaylor** [comment]
> with a config to restrict it to the shovel.

*Maybe.*

**Comment by codetaylor** [comment]
The wood chip harvest behavior has been unified with a config toggle in `1.4.0`
