### ISSUE TITLE
Allow custom duration for crafttweaker Campfire recipes

### ISSUE THREAD

**Issue by EmeraldsEmerald** [codetaylor/pyrotech#138]
Campfire recipes made using crafttweaker are limited to the default time set in the config of time per recipe. This can be annoying when every single time you want to add an item to be processed via campfire, it has to be the configured duration - no more, no less. It would be really nice to be able to individually set campfire recipe times.

**Comment by codetaylor** [comment]
Custom Campfire recipes will have independently configurable durations in `1.4.0`
