### ISSUE TITLE
Burn CT method not working properly

### ISSUE THREAD

**Issue by wormzjl** [codetaylor/pyrotech#141]
I have the following script as per example on wiki.

```
mods.pyrotech.Burn.removeRecipes(<minecraft:coal:1>);
mods.pyrotech.Burn.createBuilder("charcoal_1", <minecraft:coal:1>, "pyrotech:log_pile:*")
    .setBurnStages(2)
    .setTotalBurnTimeTicks(4 * 60 * 20)
    .setFluidProduced(<liquid:wood_tar> * 25)
    .setFailureChance(0.1)
    .addFailureItem(<pyrotech:material:0>)
    .addFailureItem(<pyrotech:material:15> * 2)
    .setRequiresRefractoryBlocks(false)
    .setFluidLevelAffectsFailureChance(true)
    .register();

```

However the replacement recipe is not shown in JEI, and there is no error in CT log. Please check if the CT method is properly implemented.

**Comment by codetaylor** [comment]
Thanks for the report!

Ok, I think I know what's going on here.

When the script is run, the removal action is aggregated as a delayed action and applied later, while the register action is applied immediately. This means the recipe gets added immediately, then later removed when the delayed actions are applied.

This is something I already solved for the bloomery builder, but missed this one.

I will resolve this for `1.3.0` which releases on CurseForge tomorrow.

**Comment by wormzjl** [comment]
great!
