### ISSUE TITLE
Crude recipe duration changes not working

### ISSUE THREAD

**Issue by BillboardEric** [codetaylor/pyrotech#144]
Title
![image](https://user-images.githubusercontent.com/8685981/62484392-18bd3880-b788-11e9-8337-c966c8acdb91.png)
![image](https://user-images.githubusercontent.com/8685981/62484402-1e1a8300-b788-11e9-9b51-6548354a9fc3.png)

I also tested the others ones (soaking pot, ect.), this is just one example.

**Comment by codetaylor** [comment]
Ok, looks like what's happened here is I forgot to apply the modifier to the displayed time in JEI. It should still function correctly, just isn't displayed in JEI correctly.

**Comment by BillboardEric** [comment]
To add, just tested the machine kiln and the opposite effect is happening.
![image](https://user-images.githubusercontent.com/8685981/62500538-ff7eb100-b7b4-11e9-80f0-5b4917572e2b.png)
![image](https://user-images.githubusercontent.com/8685981/62500548-0c9ba000-b7b5-11e9-9d93-39744c12b272.png)
![image](https://user-images.githubusercontent.com/8685981/62500579-30f77c80-b7b5-11e9-9569-193778453c6c.png)

**Comment by codetaylor** [comment]
So the waila tip is wrong?

**Comment by BillboardEric** [comment]
No sorry, I let it run and it did take the 7 minutes it said.

**Comment by codetaylor** [comment]
Ah, so the JEI is wrong?

**Comment by codetaylor** [comment]
Ok, so this was an entirely different issue, but both issues are now fixed in the next version.
