### ISSUE TITLE
Standalone version of the Soaking Pot for modpack use

### ISSUE THREAD

**Issue by inkdear** [codetaylor/pyrotech#151]
I hope this isn't considered rude, but Pyrotech's soaking pot is the best liquid-item combining crafting method I've found, and I really want to use it in my modpack, but all the other stuff in Pyrotech is already covered by an assembly of other mods, in my case. I just think the soaking pot has potential as a standalone modpack utility where the whole of Pyrotech might not be desired. I've made a vanilla-terracotta-like reskin of it for my pack, which you would be free to use if you like.

**Comment by codetaylor** [comment]
@inkdear Thanks for the compliment on the soaking pot! This isn't something that I'm going to do, though, as it involves the creation and maintenance of an entirely new, albeit redundant mod. I am available for freelance work, however. If you're interested in hiring me to create this for you, drop me a line at contact@codetaylor.com or join the Discord at [discord.codetaylor.com](http://discord.codetaylor.com) and ping me.
