### ISSUE TITLE
Custom Drying Recipes Broken?

### ISSUE THREAD

**Issue by Exsolutus** [codetaylor/pyrotech#153]
#### Issue Description

Custom Drying recipes have no progress/output

#### What Happens

I've added a custom recipe to Drying, like so:

```
CrudeDryingRack.addRecipe("died_fiber_bundle", <basketcase:item_plant_fiber>,
	<faunaandecology:fiber>, 5 * 60 * 20); // 5 minutes
```

The recipe shows up as expected in JEI, however the drying rack looks like this:

![image](https://user-images.githubusercontent.com/23705866/62822845-1a577980-bb57-11e9-8871-4f3a0af1f467.png)

#### What You Expect to Happen

The recipe ought to behave like any default drying recipe

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft: 1.12.2
* Forge: forge-14.235.28.38
* CraftTweaker: 2-1.12-4.1.19
* Dropt: 1.12.2-1.15.1
* Pyrotech: 1.12.2-1.3.2
* Athenaeum: 1.12.2-1.17.3

**Comment by codetaylor** [comment]
This has been fixed in the next patch, `1.3.3`.
