### ISSUE TITLE
Some mods add recipes that let you bypass the iron requirement for chests.

### ISSUE THREAD

**Issue by DrSquidMD** [codetaylor/pyrotech#160]
I'm aware of the following mods adding this feature. I'm not sure what could be done about it tho.
Quark adds recipes for 4 chests from logs, and for wood-dependent chests.  (Vaskii would probably be willing to add a compatibility check on their end)
Ender IO also adds an 8 logs - 4 chests recipe.
Bibliocraft also has some chests that can be made with just wood planks and slabs.

I don't know how much work you want to put into intermod compatibility, so I'm sorry if this in an inappropriate issue report.

**Comment by codetaylor** [comment]
So, here's my take on interfering with other mods' content. Pyrotech will alter vanilla content in an attempt to provide a complete, stand-alone experience, but it will not interfere with other mods' content for these reasons:

1. There are too many mods to try and keep up with content that may break progression, and
2. When Pt starts interfering with other mods, it becomes too opinionated - it is the responsibility of 
the pack designer to tailor these things to their specific design, and
3. There are existing tools that can do this that are well-implemented and battle-tested, and
4. Altering other mods' content is simply outside the scope of the project.

**Comment by codetaylor** [comment]
I'm going to go ahead and close this because I don't plan on messing with other mods' recipes. Thanks for the report tho!
