### ISSUE TITLE
No Cog Sound for Mechanical Mulcher

### ISSUE THREAD

**Issue by Zeklo** [codetaylor/pyrotech#162]
**Issue Description**
The Mechanical Mulcher doesn't produce any sound for the cog.

**What Happens**
The Mechanical Mulcher's inserted cog animates properly, but creates no sound.

**What You Expect to Happen**
I expect the Mechanical Mulcher's inserted cog to produce sound, like the other machines.

**Affected Versions**

* Minecraft: 1.12.2
* Forge: *-14.23.5.2838
* Dropt: *-1.15.1
* Pyrotech: *-1.3.6
* Athenaeum: *-1.17.3

**Comment by codetaylor** [comment]
Thanks for the report!

Fixed in `1.3.7`
