### ISSUE TITLE
Worktable.blacklistAllVanillaRecipes() does not remove blacklisted recipes from JEI

### ISSUE THREAD

**Issue by SureenInk** [codetaylor/pyrotech#165]
In my "RemoveRecipes.zs" script, I have `Worktable.blacklistAllVanillaRecipes();` However, it doesn't seem to blacklist any of the recipes. Only the recipes I have manually removed have been removed from the Worktable.

**Comment by codetaylor** [comment]
#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft:
* Forge:
* CraftTweaker:
* Dropt:
* Pyrotech:
* Athenaeum:

**Comment by SureenInk** [comment]
Minecraft: 1.12.2
Forge: 14.23.5.2836
CrT: 1.12.2-4.1.19
Dropt: 1.12.2-1.15.1
Pyrotech: 1.12.2-1.3.6
Athenaeum: 1.12.2-1.17.3

**Comment by codetaylor** [comment]
The recipes are prevented from working in the table, but still show up in JEI. They should not be shown in JEI.

**Comment by codetaylor** [comment]
Thanks for the report!

Fixed in `1.3.7`
