### ISSUE TITLE
Snow accumulates on top of machines

### ISSUE THREAD

**Issue by SlimF** [codetaylor/pyrotech#172]
Issue Description:
![2019-08-25_15 09 31](https://user-images.githubusercontent.com/6482572/63649814-30665c00-c74b-11e9-8523-4f4ad3c9f80f.png)

Just a small issue, but if your machines are outside and it snows, the snow will accumulate on top of them. 

Affected Versions:

* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* Dropt: 1.12.2-1.16.0
* Pyrotech: 1.12.2-1.3.8
* Athenaeum: 1.12.2-1.17.3

**Comment by katubug** [comment]
Hi! Sorry to bother, but this seems to be a problem again, as you can see in the issue that Snownee linked from.

Pyrotech - 1.4.17
Athenaeum - 1.17.4
Forge - 2847

I created an instance with only Pyrotech and dependencies, and created a new world. I placed all the machines in an Extreme Hills biome, and turned the weather to storm.

Snow accumulated naturally on:
- Bloomery
- Wither Forge
- Refractory Drain
- Refractory Collector
- Stone Drain

And snow layers could be placed upon:
- All of the above, and the Stone Collector

It's possible that snow would have naturally appeared on the Stron Collector with time, as some just appeared on the Strone Drain while I was writing this up.

Here are a couple of screenshots:
![2019-12-29_19 37 45](https://user-images.githubusercontent.com/20935286/71565315-22b34100-2a73-11ea-9b3a-6c0efb51e366.png)
![2019-12-29_19 37 47](https://user-images.githubusercontent.com/20935286/71565316-22b34100-2a73-11ea-8055-1c7a5883bb04.png)

There's nothing noteworthy in the latest.log. Let me know if I can provide you with any more info, or a world file or something. :)

**Comment by katubug** [comment]
Addendum - the Stone Collector did end up getting snow atop it, right as I hit send. xD

**Comment by codetaylor** [comment]
It's probably fine if snow gathers on the drains as the tops are solid faces.

The Bloomery and Wither Forge should definitely not collect snow.

I'm on the fence about the collectors... technically the top face is solid, but doesn't look like it. Yeah, I'll change the collector as well.

* Bloomery / Wither Forge
* Stone / Refractory Collector

**Comment by codetaylor** [comment]
Should be fixed in today's patch `1.4.19`

**Comment by katubug** [comment]
Thanks a bunch!
