### ISSUE TITLE
random crashs

### ISSUE THREAD

**Issue by Zack7292** [codetaylor/pyrotech#174]
Before starting, i skip a lot of point since they wasn't touching this crash (jsut to warn)

#### What Happens

* Describe what happens: i lunch my wolrd and few secondes after it randomly crash
* Describe, in detail, the steps required to reproduce the issue : join a world and try to play

*[/replace]*

#### What You Expect to Happen

 i expect to play into my world  ._.

#### Crash Log
crash log: https://hastebin.com/ikufohuzec.rb  (mod list included with the versions)

#### Affected Versions

* Minecraft:
* Forge: 1.12.2-forge1.12.2-14.23.5.2838
* CraftTweaker: NONE
* Dropt: 1.16.0
* Pyrotech: 1.3.9
* Athenaeum: 1.17.3

**Comment by Zack7292** [comment]
i actually don't  really understand it though since i jsut lunch my game with it and the other mod and it do this and after it crashed randomly after only doing like a move, after i delete it it stopped , but maybe it wasn't this mod but actualy to be fair this mod was the only one who was asking me to reloade or something like this cause to recipe thing (not rlly got time to rea mush)

**Comment by codetaylor** [comment]
> Please provide more of the stack trace, not just the crash snippet. It's usually found toward the end of the log, before the crash snippet.

**Comment by Zack7292** [comment]
srry i can't really put it anywhere sinc eits to big so ima put it here

**Comment by Zack7292** [comment]
so there a mediafire link : https://www.mediafire.com/file/0c8mhnr5aw5tapz/2019-08-25-3.log/file

**Comment by codetaylor** [comment]
Thanks for providing the log, however, I don't see anything that indicates what caused the crash.

If I had to guess, I'd say it was probably Optifine.

```
java.lang.StackOverflowError
    at net.optifine.reflect.Reflector.handleException(Reflector.java:1352)
    at net.optifine.reflect.Reflector.callInt(Reflector.java:879)
```

**Comment by Zack7292** [comment]
ok thaks tho with the helping but i remove your mod and 2 other then i can't remember and it wasn't optifin and after it work perfecly
