### ISSUE TITLE
Bone meal recipe failure.

### ISSUE THREAD

**Issue by Roonas** [codetaylor/pyrotech#18]
#### Issue Description
Bone meal cannot be made from bones or bone blocks on granite and iron anvils.

#### What Happens
Attempting to make bone meal when hammering bones or blocks of bones on a granite or iron anvil fails to work.

#### What You Expect to Happen
Bone meal to be made from hammers on anvils, as per the JEI recipe.

#### Script
N/A

#### Crash Log
N/A

#### Affected Versions

* Minecraft: 1.12.2
* Forge: forge1.12.2-14.23.5.2836
* Dropt: 1.14.0
* Pyrotech: 1.0.1
* Athenaeum: 1.17.1

**Comment by codetaylor** [comment]
I think this is an oversight on my part, the recipes are conflicting and it's always choosing the pickaxe recipe first.

![image](https://user-images.githubusercontent.com/1240716/59537458-7f6e5600-8eab-11e9-8efc-9daf25c8e2e4.png)
![image](https://user-images.githubusercontent.com/1240716/59537501-a0cf4200-8eab-11e9-8f21-7c4aa1d97c56.png)
