### ISSUE TITLE
Request - Tough As Nails not longer updated & in need of new survival mod

### ISSUE THREAD

**Issue by Pseudohuman93** [codetaylor/pyrotech#182]
Hello, Taylor

I just wanted to inform you that Tough As Nails is not longer going to be updated. Therefore, any compatibility attempts can lead to crashes that could not be fix by the T.A.S author.

Thus, since you seem keen to develop "survival-related" mods, would you consider making your own version of T.A.S. Of course, not an exact copy, but something that is better and (in your own way) complement Pyrotech?

Thanks in advanced for your response! :)

**Comment by codetaylor** [comment]
What kind of features would the new mod have?

I'm not too familiar with TAN features, other than the thirst and temperature features.

**Comment by Pseudohuman93** [comment]
Thank you for answering, Taylor!
I feel like “thirst” and “temperature” are basic for a survival mod.
Now, a feature that I’ve seen in the past, that hasn’t been touched again is: gravity. This feature was implemented by the mod: “Enviromine”. The “gravity” feature made cave exploration/mining and building, more challenging; since cave-ins where guaranteed if the passages didn’t have supports. 
Another feature that wasn’t touch again is: “sanity”. Basically, if you keep playing without sleep, it will affect your health and provoke hallucinations. After three days without sleeping, you could die.
Another feature that could be explore is “food degradation” and/or “nutrition”. For “food degradation” you could think the following: if food is not preserved in a special kind of storage, it will rot/go bad eventually. Furthermore, if the player has food in his/her inventory while he/she is in the desert, the food rots faster; as if the player is currently in a cold biome, the food’s degradation slows down.
Now, this feature was also explored by “Enviromine” and “Glenn’s Gases”: "Toxic Fumes"; like carbon dioxide or sulphur gas .These appear as you go deeper into the caves…and the risk of explosions due to one of those gases…if you dare to lit a torch in a cave or the risk of asphyxia.
Additionally, an ideal compatibility would be with Primal Core, as it also focusses on survival…
I hope my suggestions prove useful to you. Once again, these are just suggestions, so feel free to pick whichever sounds fun to you to develop…and hopefully make a mod that becomes a great companion to Pyrotech! 😊

**Comment by Xorbah** [comment]
That's an awful lot you're asking for.

**Comment by Exsolutus** [comment]
Thirst, temperature, and gravity (with supports like Environmine or TerraFirmaCraft) mechanics would be the essential three. I haven't seen any mods which provide such gravity mechanics for 1.12+.

**Comment by Pseudohuman93** [comment]
> That's an awful lot you're asking for.

That's why I said: "suggestions" xP

I know Taylor will not add all those features since it's a lot of work...but hopefully, this will inspire him to make a unique survival mod

Pyrotech is an A+ quality mod, can't wait to see what he will come up to next time :)

**Comment by WarlordWossman** [comment]
Thirst and temprature would be the most interesting things in my opinion, currently it's tough to work with TAN (pun intended) and their systems are not as mature as I would have hoped.
Personally I like the idea of a worldgen that seperates between sea water, fresh water and (dirty) swamp water, a cool idea would be getting salt from ocean water that could be used for various things like conserving foods or turning milk into cheese in the soaking pot.

**Comment by Xelbayria** [comment]
I would suggest that you check out a mod called "Schopcraft" It has temperature and thirst.. it's a little more better than TAN. TAN's temperature is too simple and flawed.
