### ISSUE TITLE
[Question] CraftTweaker Documentation

### ISSUE THREAD

**Issue by UnlimatedStone9** [codetaylor/pyrotech#183]
Sorry to bother, maybe I'm just missing something but by the looks of it this mod supports CraftTweaker, however I cannot seem to locate any documentation of such support.
Correct me if I'm wrong please. Thanks!

**Comment by codetaylor** [comment]
Here's the CrT docs: https://pyrotech.readthedocs.io/en/latest/, and you're welcome to [join the Discord](http://discord.codetaylor.com) if you have any more questions. :)
