### ISSUE TITLE
PyroTech Pitkiln has trouble rendering item textures

### ISSUE THREAD

**Issue by UnlimatedStone9** [codetaylor/pyrotech#184]
Placing a log that uses an item texture on top of the Pitkiln causes X-Rayesque glitch

I would've hoped to expect it use the log block texture or a generic wood texture provided by PyroTech but it appears not.

The mods present are of course PyroTech and it's dependencies, and TerraFirmaCraft (which adds the log items)

![image](https://user-images.githubusercontent.com/40124890/64294092-f0328500-cf65-11e9-9144-29740631a5c7.png)

TFC replaces the logs with log item textures when in an inventory/GUI

![image](https://user-images.githubusercontent.com/40124890/64294160-148e6180-cf66-11e9-8b44-1f984e3ff185.png)

**Comment by codetaylor** [comment]
Yeah, that's a limitation of Pyrotech's interaction system. For now I would recommend not using items that don't use a block model.

**Comment by UnlimatedStone9** [comment]
I'll keep that in mind, thanks Taylor!
