### ISSUE TITLE
Creeper Explosion on Lit Campfire Causes World/Game Crash

### ISSUE THREAD

**Issue by WittyWhiscash** [codetaylor/pyrotech#189]
#### Issue Description

A creeper explosion next to a lit campfire causes a game crash.

#### What Happens

When the creeper explodes next to a lit campfire, the game freezes, then crashes with the same stacktrace error.

Steps to reproduce:
1. Create a new world, with cheats so you can spawn in the proper items to recreate the crash.
2. Set up a campfire, and light it with a flint and tinder.
3. Place a spawn creeper egg next to you.
4. Let the creeper explode. The game should crash.

#### What You Expect to Happen

The campfire should be destroyed in the explosion, the player should die, and be able to respawn without a crash.

#### Crash Log

Initial crash log:
https://paste.dimdev.org/akubemozus.mccrash

Reproduction attempt 1:
https://paste.dimdev.org/sovinahoko.mccrash

Reproduction attempt 2:
https://paste.dimdev.org/acucucowav.mccrash

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft: 1.12.2
* Forge: 1.12.2-14.23.5.2838
* CraftTweaker:1.12.2-4.1.19
* Dropt: 1.12.2-1.16.0
* Pyrotech: 1.12.2-1.3.12
* Athenaeum: 1.12.2-1.17.3

**Comment by codetaylor** [comment]
Thanks for the report!

Pretty sure I see what the issue is. Do you have the Bloomery module disabled by chance?

**Comment by WittyWhiscash** [comment]
In fact I do. 
![image](https://user-images.githubusercontent.com/21300678/64481273-f5761680-d195-11e9-9cb4-67521e15adba.png)
