### ISSUE TITLE
Syntax error(?) in documentation

### ISSUE THREAD

**Issue by Roonas** [codetaylor/pyrotech#20]
[The book has, what appears to be some syntax errors for multi word entries.](https://cdn.discordapp.com/attachments/400504502551052288/589204287486296065/unknown.png)

Affected Versions
Minecraft: 1.12.2
Forge: forge1.12.2-14.23.5.2836
Dropt: 1.14.0
Pyrotech: 1.0.1
Athenaeum: 1.17.1

**Comment by codetaylor** [comment]
Can you be more specific? I don't know what I'm looking at.

**Comment by Roonas** [comment]
You can see in the book some of the entries read something like "_clay, lump of_" or "_shard, bone and flint_" which doesn't make sense grammatically.

**Comment by codetaylor** [comment]
Yeah, this was a design decision to group things in a specific way when looking at the alphabetical index.
