### ISSUE TITLE
Sawmill produces fewer planks than the chopping block

### ISSUE THREAD

**Issue by belathus** [codetaylor/pyrotech#201]
#### Issue Description

Sawmill produces fewer planks than the chopping block.

#### What Happens

I've noticed that when using a chopping block to convert logs to planks, crude axes return 1 plank, flint tier axes return 2 planks, iron returns 3 planks, and diamond tier axes produce 4 planks.

However, when using the sawmill, you generally get 1 fewer planks. The stone saw blade returns 1 plank, flint and iron tier produces 2 planks, and diamond produces 3 planks.

#### What You Expect to Happen

I expected the sawmill to have a similar output to the chopping block; iron saw blade to produce 3 planks and diamond saw blade to produce 4 planks.

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft: 1.12.2
* Forge: 14.25.5.2838
* CraftTweaker: 4.1.19
* Dropt: 1.16.1
* Pyrotech: 1.3.13
* Athenaeum: 1.17.4

**Comment by codetaylor** [comment]
The chopping block does give more planks, but it also costs more in terms of tool durability, device durability, hunger, and player time.

The sawmill gives slightly fewer planks, but has the benefit of not causing hunger, not wearing out, causing less durability damage to the sawblade than to tools, and freeing up the player to do other things while it's working. Also, unlike the chopping block, it can be automated.

**Comment by belathus** [comment]
Ah, so it is intentional. Interesting.
