### ISSUE TITLE
Fossil ore duplication

### ISSUE THREAD

**Issue by SSKirillSS** [codetaylor/pyrotech#212]
**Versions:**
pyrotech-1.12.2-1.4.2
dropt-1.12.2-1.16.1
athenaeum-1.12.2-1.17.4
forge-1.12.2-14.23.5.2847

**Description:**
When fossil ore is destroyed with a silk touch enchanted pickaxe, both ore and bone fragments are given.

**How to reproduce:**
1. Enchant any pickaxe to silk touch
2. Mine fossil ore

**Comment by codetaylor** [comment]
Fixed in `1.4.3`
