### ISSUE TITLE
Biomes o' Plenty; Natura compatibility

### ISSUE THREAD

**Issue by Komplein** [codetaylor/pyrotech#215]
Modded wood doesn't have chopping board recipes and can be crafted into planks in inventory as default minecraft.

**Comment by codetaylor** [comment]
Please elaborate.

**Comment by jonthemoron** [comment]
I think he's referring to how Pyrotech doesn't natively add recipes for all modded logs on the chopping block. I would suggest using CraftTweaker to add the recipes/adjust the wood recipes to be accurate.

**Comment by codetaylor** [comment]
My concern is that it *should* be generating compat for most modded logs, planks, and slabs, provided the wood compat config is refreshed after the initial run or after any new mods are added / removed.

https://pyrotech.readthedocs.io/en/latest/woodcompat/
