### ISSUE TITLE
Can't get Mason Bricks

### ISSUE THREAD

**Issue by TheSexyYeti** [codetaylor/pyrotech#219]
I can't get mason brinks because the granite or ironclad anvil won't let me place stone bricks on them. The manual and JEI say I have to put stone bricks on one of those anvils and use a flint or above pickaxe to get a stone brick slab. Then do the same thing with the slab to get the bricks. But neither of the anvils will let me place a block of stone bricks on either of them.

**Comment by codetaylor** [comment]
Are you playing a modpack or have you otherwise altered the recipes?

**Comment by codetaylor** [comment]
I'm unable to reproduce this.

![2019-10-21_15-15-38](https://user-images.githubusercontent.com/1240716/67247301-c51ccb80-f415-11e9-83fd-cb4689319345.gif)

**Comment by TheSexyYeti** [comment]
I'm playing on a modpack I'm developing. Do you have any idea what could possibly be conflicting with this?. The only thing that I could think is Better with mods. But I'm not sure if it has any changes that involve stone brick.

**Comment by codetaylor** [comment]
> Do you have any idea what could possibly be conflicting with this?

I have no idea. You could try disabling mods one at a time or in groups until the problem goes away.

**Comment by codetaylor** [comment]
@TheSexyYeti Were you able to solve this?
