### ISSUE TITLE
Better feedback for running recipe

### ISSUE THREAD

**Issue by Kurtchekov** [codetaylor/pyrotech#22]
#### Issue Description

It's difficult to know when certain items are done processing in the soaking pot, drying rack, campfire, kiln, oven or even sawmill, specially for people with colorblindness like me.

Any chance we can have better visual cues for those machines? For example:

* Soaking Pot: items being processed bob up and down in the fluid, while fully processed or invalid items simply stay put, as it is right now.
* Drying Rack: water dripping particles for items being processed.
* Campfire, Kiln and Oven: tiny flame particles could come out of the upper part of those machines during the processing of items.
* Sawmill: sawmill blade could glow, getting hot as it cuts through items.

Other than that, I have to say this mod is really damn good, I thoroughly enjoy the game design decisions and balance put into this. Thank you for putting so much effort into it!

**Comment by codetaylor** [comment]
Thank you for your kind words!

I was using Hwyla when playtesting, which gives progress info for all the stuff, so I didn't really notice some of the missing cues. I have plans to implement support for TOP as well.

* Soaking Pot: I agree that this could use some better visual cues. My initial thought in my notes was to add bubble particles, which would be easier to do than the moving item. Maybe both?
* Drying Rack: The dripping particles would be great!
* Campfire: The campfire already has some visual cues in that it will produce considerably more smoke when the item is done cooking (when it starts to turn to burned food, if it is food).
* Kiln, Oven: All of the combustion machines will produce large smoke particles only when actively working on a recipe.
* Sawmill: The sawmill will produce smoke when working as well as spewing block particles from the top.

**Comment by Kurtchekov** [comment]
Oh, I was using The One Probe, didn't know that it'd show more meaningful information in Hwyla...

* Campfire: I noticed, but it can be a bit confusing if I have multiple machines around the same place producing the same kind of particles, particle amount being the only way to know when it's done can become tricky.

About all the machines that use solid fuel, I think I now know what the problem is: as a beginner, I'm not aware of the smoke mechanics and also don't want to waste precious fuel, so whenever I put those machines to work, I already have the ingredients in place even before I light the fire. When I see the smoke coming out of those machines, the first thing that comes to mind is that the smoke is being generated by the mere fact that the machine is burning fuel, not that it's running a recipe. To be able to understand that smoke is related to latter rather than the former, I'd need to keep the machine running without any products being produced while also paying attention to it, something that would generally be unusual since I'd much more likely be running around trying to find something else to be processed or simply try to put of the fire to save fuel.

Perhaps it'd be a more meaningful design paradigm if, rather than more or bigger (in most cases, smoke being made), we could go for more distinct cues, like using different particle effect or specific audio cues when a recipe is running, as opposed to a machine merely being on.

**Comment by codetaylor** [comment]
> more distinct cues, like using different particle effect

I agree.

In a previous feature iteration, I added:

* Worktables: bone meal particles to indicate recipe progress
* Anvils: bone meal particles to indicate recipe progress

In this next feature iteration, I can add:

* Soaking Pot: bubble particles while working
* Drying Rack: water dripping particles while working
* Campfire, Kiln and Oven: flame particles while working
* Chopping Block: bone meal particles to indicate recipe progress

I'm not sure about:

* Sawmill: sawmill blade glowing while working

I'm not sure if the glowing blade would be possible using the interaction framework that I've set up. 
 I'd have to do a little research on that. Currently, while the sawmill is working, it will spew block breaking particles for the block type currently being processed.

**Comment by Kurtchekov** [comment]
Yeah, the sawmill suggestion isn't that great, I just didn't feel like complaining about it without suggesting something else instead =P

Maybe it'd be better to simply have 2 different sound effects for the sawmill, something like this https://freesound.org/people/astrar/sounds/349492/ while active but not running any recipe and this https://freesound.org/people/kolczok/sounds/198984/ whenever it processes a valid recipe. Another example of those two "state sounds" coming from the same machine: https://freesound.org/people/derjuli/sounds/448133/

I've been playing this mod A LOT with my mate and gotta say that you've done an amazing job, I trust you'll decide what's best ^^

**Comment by codetaylor** [comment]
What do you think of this?

![2019-07-05_15-45-39](https://user-images.githubusercontent.com/1240716/60747722-39e9f980-9f3c-11e9-9768-6c7f8ff11b15.gif)

**Comment by Kurtchekov** [comment]
It's simple and unambiguous, not to mention it has the same meaning other entities use those particles for, I like it! ^^

**Comment by codetaylor** [comment]
![campfire-particles](https://user-images.githubusercontent.com/1240716/60759211-25f2d600-9fd6-11e9-8bc4-a4d1a1b42a35.gif)

**Comment by codetaylor** [comment]
![2019-07-06_11-38-00](https://user-images.githubusercontent.com/1240716/60760042-69a00c80-9fe3-11e9-85b0-25aa262596c2.gif)

**Comment by codetaylor** [comment]
![2019-07-06_11-43-18](https://user-images.githubusercontent.com/1240716/60760046-73297480-9fe3-11e9-8563-3d80e0cb8d6b.gif)
