### ISSUE TITLE
Custom Rocks for compat with Underground Biomes

### ISSUE THREAD

**Issue by xlea99** [codetaylor/pyrotech#222]
Hello! I love this mod and am really hoping to include it in a modpack I've been working on. Just wondering if there's any way compatibility could be added with Underground Biomes (really just new rock types for each UB stone) or even just CraftTweaker support to add in your own rocks like you can with Ores/Blooms. 

Thanks so much for your time!

**Comment by codetaylor** [comment]
Thank you :)

Yes, custom rock support is planned, see #50 

If you'd prefer not to wait, you can use ContentTweaker to create your own rock items and Dropt to modify block drops. The rocks won't have the same properties as the Pyrotech rocks, but it's probably about all you can do right now.
