### ISSUE TITLE
How do you get wood tar?

### ISSUE THREAD

**Issue by TheSexyYeti** [codetaylor/pyrotech#226]
I've been trying to figure out how to get wood tar. The manual or JEI doesn't really say. Do you get it from living tar?. Because I thought that was merely a fuel source.

**Comment by codetaylor** [comment]
Wood tar is a byproduct of pit burning and is explained in the Patchouli guidebook. Basically do a pit burn with a collector at the bottom to collect the tar.

If you have more questions, you're welcome to join the Discord server: http://discord.codetaylor.com
