### ISSUE TITLE
Game crashing when setting fire to wood using campfires

### ISSUE THREAD

**Issue by jamesreii** [codetaylor/pyrotech#231]
#### Intro

Please follow the template when submitting an issue.

If you are submitting a suggestion, feature request, or idea, please delete this template and follow the guidelines found in the README.md file.

If you do not follow the template or guidelines, your issue will be flagged as `invalid` and may be immediately closed.

Text placed within *[replace]* tags may be omitted and replaced with your text.

#### Issue Description

Minecraft crashes when I set fire to a campfire on top of logs 

If this issue occurs in a modpack, please report this to the modpack author. Also, please take the time to look at existing issues to ensure you don't create a duplicate. You may remove this line and place your issue description here.

*[/replace]*

#### What Happens

Lit campfires on top of logs crash my game
After I place an unlit campfire with no logs down on top of minecraft block logs and ignite it, my game crashes, although the first time i've tried this, I didnt crash but froze for like 2 seconds and the whole vein of log turned into this magma like block

*[/replace]*

that the logs would all burn 

*[replace]*

that all the logs would turn into those magma block things or burn 

*[/replace]*

#### Script

*[replace]*

If your issue involves a CraftTweaker script, please place a **LINK** to your script here.

**DO NOT** paste your script here. Please use a service such as pastebin, hastebin, or gist.

*[/replace]*

#### Crash Log

*[replace]*

If your issue involves a crash log, please place a **LINK** to your crash log here.

**DO NOT** paste your crash log here. Please use a service such as pastebin, hastebin, or gist.

*[/replace]*

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft:
* Forge:
* CraftTweaker:
* Dropt:
* Pyrotech:
* Athenaeum:

**Comment by codetaylor** [comment]
Crash report: https://hastebin.com/raw/ecexayajij
