### ISSUE TITLE
Campfire recipes don't respect output quantity (or should be corrected in JEI)

### ISSUE THREAD

**Issue by nihiltres** [codetaylor/pyrotech#235]
#### Issue Description

While furnace recipes take a single input item per operation, they can produce stacks of output items. For example, the Raw Squid item from Mystical World produces two Calamari items when cooked. In JEI, it's indicated that the recipe is the same for the Campfire: one Raw Squid should produce two Calamari. However, if the recipe is followed in-game, the campfire produces only one Calamari.

#### What Happens

1. Install JEI, Mystical World, and Pyrotech, plus all necessary dependencies.
2. View the Furnace and Campfire "uses" for the Raw Squid in JEI; note that both recipes appear to produce two Calamari.
3. Create and light a Campfire and acquire one Raw Squid.
4. Cook the Raw Squid on the Campfire.
5. Retrieve the result once cooked; note that only one Calamari is retrieved.

#### What You Expect to Happen

Either the Campfire recipe should be "corrected" for JEI and display an output of one Calamari, or the Campfire should output two Calamari. This should apply for other adapted Furnace recipes that produce stacks of greater than one item, too, but this is both a good example that's "baked into" a popular mod, and how I discovered the issue.

#### Script

Not applicable.

#### Crash Log

Not applicable.

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft: 1.12.2
* Forge: 14.23.5.2831
* CraftTweaker: 1.12.2-4.1.19
* Dropt: 1.12.2-1.16.1
* Pyrotech: 1.12.2-1.4.7
* Athenaeum: 1.12.2-1.17.4

**Comment by codetaylor** [comment]
Thanks for the report!

Was able to reproduce with:
```
furnace.remove(<minecraft:cooked_chicken>);
furnace.addRecipe(<minecraft:cooked_chicken> * 2, <minecraft:chicken>);
```

This has been fixed in `1.4.8` and will be available later today.
