### ISSUE TITLE
Endless slag

### ISSUE THREAD

**Issue by pawIka** [codetaylor/pyrotech#237]
Hi, sorry my english

An endless amount of ore slag can be obtained by interrupting the process of ore smelting in the furnace. Without waiting for the end of the smelting of ore into raw materials, just break the furnace, then resume the process. Set the furnace and start melting the ore. Ore will not be wasted, and slag will always fall.

* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* CraftTweaker: 1.12.2-4.1.19
* Dropt: 1.12.2-1.16.1
* Pyrotech: 1.12.2-1.4.7
* Athenaeum: 1.12.2-1.17.4

**Comment by SSKirillSS** [comment]
I confirm this issue.
