### ISSUE TITLE
Explosions only dropping a single component item

### ISSUE THREAD

**Issue by Divineaspect** [codetaylor/pyrotech#239]
Rocks, dirt clumps, sand, etc are quite problematic when fighting the wither. If possible could you make explosions only drop one of their thing, so the problem isn't a multiplier on the loose objects on the ground issues?

**Comment by codetaylor** [comment]
In `1.4.10` see `plugin.Dropt.cfg` -> `REDUCE_EXPLOSION_DROPS`
