### ISSUE TITLE
Worktable voiding stored items.

### ISSUE THREAD

**Issue by Roonas** [codetaylor/pyrotech#24]
**Issue Description**
Worktable voids items stored in it's 'shelf' when the table breaks from being used too much.

**What You Expect to Happen**
Worktable should drop it's items when broken from use.

**Script**
N/A

**Crash Log**
N/A

**Affected Versions**
Minecraft: 1.12.2
Forge: forge1.12.2-14.23.5.2836
Dropt: 1.14.0
Pyrotech: 1.0.4
Athenaeum: 1.17.1

**Comment by codetaylor** [comment]
Thanks for the report!
