### ISSUE TITLE
Add `gear*` oredict to cogs

### ISSUE THREAD

**Issue by SimonMeskens** [codetaylor/pyrotech#243]
Cogs should probably have `gear*` (for example `gearIron`) oredicts, so they become compatible as gears in recipes that require gears. Also, mods like Immersive Engineering will generate recipes to create them with machines.

**Comment by codetaylor** [comment]
Thank you for the suggestion!

I think that this is very contextual change and is ultimately up to the pack maker to tailor to their desired experience. Cogs were designed to stand apart from the gears in other mods with respect to their function and purpose, yet be similar in appearance.

In situations like these where it could go either way and really boils down to a matter of preference, I will fall back to my preference, which is to leave the cogs out of the gears oredict.

**Comment by SimonMeskens** [comment]
Perfect! Thanks for confirming :)
