### ISSUE TITLE
Mechanical Compactor, when containing redstone, causes a considerable framerate drop

### ISSUE THREAD

**Issue by belathus** [codetaylor/pyrotech#244]
## Issue Description

Putting items into the mechanical compactor causes significant framerate loss -- I'm going from 60 to 9-10, until it finishes compacting or I otherwise empty the machine. Leaving an incomplete recipe in the machine also causes framerate loss.

I've tried redstone and copper slag, both having the same result.

Interestingly, the compacting bin is not affected by this; I get no significant framerate loss.

I tried using LagGoggles to get it to point to the machine, but LagGoggles didn't report any particular issues that I could see. Even so, my framerate goes back to normal the moment I empty the compactor.

#### What Happens

* Place items into mechanical compactor.
* Experience framerate loss until it is empty again.

#### What You Expect to Happen

Not have framerate loss.

#### Script

N/A

#### Crash Log

N/A

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* CraftTweaker: 4.1.19
* Dropt: 1.16.1
* Pyrotech: 1.4.5
* Athenaeum: 1.17.4

**Comment by belathus** [comment]
Interestingly, I am now having issues duplicating my own reported issue...

I've even got the same setup as before. I guarantee this was happening before, but it isn't happening at all now. I'll continue to keep my eye on it to see if I can figure anything out.

**Comment by codetaylor** [comment]
I'm going to go ahead and close this. You're welcome to re-open it if you're able to reproduce it.
