### ISSUE TITLE
Worktable cannot detect CraftTweaker's .transformDamage tag, perhaps others too.

### ISSUE THREAD

**Issue by UnlimatedStone9** [codetaylor/pyrotech#250]
When using a recipe that uses the .transformDamage() tag instead of damaging said item it consumes it.
The issue likely occurs with other CraftTweaker tags and perhaps in normal vanilla recipes?

#### What You Expect to Happen

The tool to be damaged and left on the table.

#### Affected Versions

* Minecraft: 1.12.2
* CraftTweaker: 1.12-4.1.19
* Pyrotech: 1.12.2-1.4.13

**Comment by codetaylor** [comment]
I'm unable to reproduce this with both the wooden and stone worktable using the following recipes:

```
import mods.pyrotech.Worktable;

Worktable.addShapeless("worktable_recipe", <minecraft:cobblestone>, [<minecraft:iron_pickaxe:*>.transformDamage(1), <minecraft:stone>]);

recipes.addShapeless("vanilla_recipe", <minecraft:stone>, [<minecraft:iron_axe:*>.transformDamage(1), <minecraft:dirt>]);
```

**Comment by codetaylor** [comment]
I also tried `addShaped` with the same results.

```
import mods.pyrotech.Worktable;

Worktable.addShaped("worktable_recipe", <minecraft:cobblestone>, [[<minecraft:iron_pickaxe:*>.transformDamage(1), <minecraft:stone>]]);

recipes.addShaped("vanilla_recipe", <minecraft:stone>, [[<minecraft:iron_axe:*>.transformDamage(1), <minecraft:dirt>]]);
```

**Comment by codetaylor** [comment]
OP was using `.transformDamage()` on a GregTech tool. Because GT tools use NBT for damage instead of the meta value, CrT's `.transformDamage()` will not work.
