### ISSUE TITLE
Camp Fire and Heat (Tough As Nails Compat)

### ISSUE THREAD

**Issue by sulkbliss** [codetaylor/pyrotech#254]
*The camp fire doesn't seem to emit heat when fiber torches do*

I'm using this with Tough As Nails, a temperature-centric mod. I realize the mod is old but it seems to be stable still.

I'm wondering if there's a way to make the campfire emit heat or if I can increase the amount it may already emit. I did not see anything in the configuration files for that.

#### Affected Versions

* Minecraft: 1.12.2
* Forge: #2847
* CraftTweaker: 4.1.19
* Dropt: 1.12.2-1.16.1
* Pyrotech: 1.4.11
* Athenaeum: 1.12.2-1.17.4

**Comment by codetaylor** [comment]
Yes, please see https://github.com/codetaylor/pyrotech/issues/123

At the bottom there is an example to get the Campfire working with TaN.

**Comment by sulkbliss** [comment]
Oh okay awesome, thanks so much. How do I add that to my game? Do I paste that 'snippet' into a text file and drop it somewhere? Or replace a line with it somewhere?

**Comment by codetaylor** [comment]
It's added to one of TaN's config files:
![image](https://user-images.githubusercontent.com/1240716/70195626-14b01180-16bb-11ea-8ddd-626033e11ffe.png)

If you have more questions, you're welcome to join the Discord: https://discord.gg/HY69E8X

**Comment by sulkbliss** [comment]
Thanks!

**Comment by codetaylor** [comment]
You're welcome :)
