### ISSUE TITLE
The chopping block in pyrotechnics won’t work with logs.

### ISSUE THREAD

**Issue by acepitar** [codetaylor/pyrotech#255]
#### Intro

Please follow the template when submitting an issue.

If you are submitting a suggestion, feature request, or idea, please delete this template and follow the guidelines found in the README.md file.

If you do not follow the template or guidelines, your issue will be flagged as `invalid` and may be immediately closed.

Text placed within *[replace]* tags may be omitted and replaced with your text.

#### Issue Description

*[replace]*

If this issue occurs in a modpack, please report this to the modpack author. Also, please take the time to look at existing issues to ensure you don't create a duplicate. You may remove this line and place your issue description here.

*[/replace]*

#### What Happens

*[replace]*

* Describe what happens
* Describe, in detail, the steps required to reproduce the issue

*[/replace]*

#### What You Expect to Happen

*[replace]*

* Describe what you expect to happen

*[/replace]*

#### Script

*[replace]*

If your issue involves a CraftTweaker script, please place a **LINK** to your script here.

**DO NOT** paste your script here. Please use a service such as pastebin, hastebin, or gist.

*[/replace]*

#### Crash Log

*[replace]*

If your issue involves a crash log, please place a **LINK** to your crash log here.

**DO NOT** paste your crash log here. Please use a service such as pastebin, hastebin, or gist.

*[/replace]*

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft:
* Forge:
* CraftTweaker:
* Dropt:
* Pyrotech:
* Athenaeum:

**Comment by mr-V01d** [comment]
Anyone encoring same issue: delete pyrotech config and restart minecraft.

If i understood correctly, some mod that change wood to planks receipt(NoTreePunching, ...) can remove ability to place wood on chopping block.
