### ISSUE TITLE
ToP error when viewing filled Bloomery

### ISSUE THREAD

**Issue by katubug** [codetaylor/pyrotech#258]
![2019-12-13_20 21 56](https://user-images.githubusercontent.com/20935286/70842279-33af5180-1de7-11ea-8cff-ee88dcf51ae0.png)

#### Issue Description
As you can see in the above image, there's an error when viewing the Bloomery. It occurs from any angle, and when looking at either the top or bottom of the machine. It continues to occur until the Bloom itself is removed.

#### Steps to Reproduce
1. In instance with only Pyrotech and The One Probe, place a Bloomery.
2. Place Iron or Gold Ore inside, along with Coal Blocks, and process the ore.
3. Without removing the subsequent Ash or Blooms, view side of Bloomery.
4. Remove Ash but leave Bloom in place, and Bloomery.

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 2847
* The One Probe: 1.4.28
* Dropt: 1.16.1
* Pyrotech: 1.4.14
* Athenaeum: 1.17.4

**Comment by codetaylor** [comment]
Thanks for the report!

Fixed in `1.4.15` and will be out later today
