### ISSUE TITLE
Missing Localization Key for tile.pyrotech.pile_ash_block.name

### ISSUE THREAD

**Issue by Timeslice42** [codetaylor/pyrotech#259]
Missing a localization key (in en_us at least) for `tile.pyrotech.pile_ash_block.name`.

* Pyrotech: 1.4.14
* Athenaeum: 1.17.4

**Comment by codetaylor** [comment]
I don't understand.

Pyrotech uses `pyrotech:pile_ash` and the localization key is `tile.pyrotech.pile_ash.name=Ash Pile`.

![2019-12-14_08-49-26](https://user-images.githubusercontent.com/1240716/70851804-d3ec9100-1e4e-11ea-828b-6764bcd24ba5.png)

**Comment by Timeslice42** [comment]
I'm talking about the block, not the item.
https://i.imgur.com/msKWHO6.png

Everything the player can look at needs a name.

**Comment by codetaylor** [comment]
Thanks for the clarification -- I understand now. :)

I was also talking about the block, not the item. We are just talking about two different blocks and that's where I got confused.

![image](https://user-images.githubusercontent.com/1240716/70865331-31491680-1f11-11ea-8f4a-d398279886cc.png)

**Comment by Timeslice42** [comment]
Gotcha :)
