### ISSUE TITLE
Guidebook bug: The Campfire entry has broken links

### ISSUE THREAD

**Issue by katubug** [codetaylor/pyrotech#270]
#### Issue Description
When reading the Campfire entry, it lists 4 sub-pages: Craft Tinder, Place Tinder, Add logs, Ignite

Those entries are visible if one continues to turn the pages in that entry, but clicking on the links takes you instead to the Introduction. Hovering over the links produces a tooltip that says "INVALID ANCHOR:ignite" etc. I expected those links to take me to the relevant entries.

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 2847
* CraftTweaker: n/a
* Dropt: n/a
* Pyrotech: 1.4.19
* Athenaeum: 1.17.4
* Patchouli: 1.0-20

**Comment by codetaylor** [comment]
Thanks for the report! Should be fixed in `1.4.20`
