### ISSUE TITLE
Optifine causes odd shadows on some block models

### ISSUE THREAD

**Issue by notWaterGuy12** [codetaylor/pyrotech#277]
#### Issue Description

When Optifine is present, shadows occur on the chimneys of the stone oven and refractory oven.

#### What Happens

Dark patches occur on the tops of the chimneys of the previously mentioned blocks. Not shown in the imgur album is that it occurs on all blocks with a top half if shaders are being used. https://imgur.com/a/1WNo0yK

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* Dropt: 1.16.1
* Pyrotech: 1.4.20
* Athenaeum: 1.17.4
* Optifine: E3

**Comment by codetaylor** [comment]
I don't support optifine.
