### ISSUE TITLE
ticking entity

### ISSUE THREAD

**Issue by captcookie** [codetaylor/pyrotech#28]
#### What Happens
I was using the stone door on top of a woodpile to attempt to get wood tar. After lighting and closing the stone door above the woodpile I saw the woodpile ignite and now the server crashes. I did have a stone collector and drain attach to the setup.

#### Crash Log

https://pastebin.com/ygGwwxUK

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft:1.12.2
* Forge: 2838
* CraftTweaker:n/a
* Dropt:latest
* Pyrotech:1.04
* Athenaeum:latest

**Comment by codetaylor** [comment]
Was the door on top of the wood pile...?

The doors should be placed on the side of the wood pile, flush with the material you're burning.

Is the server still crashing? Are you able to provide a screenshot of your setup?
