### ISSUE TITLE
Game crash when craft a new item

### ISSUE THREAD

**Issue by MokoBlack** [codetaylor/pyrotech#281]
Text placed within *[replace]* tags may be omitted and replaced with your text.

#### Issue Description

 Game crash when craft pyrotech item which i haven t craft before

#### Steps to Reproduce

1.open the inventory
2.Put the materials needed to make this item into the craft grid
3.Take out the crafted item
4.game crashed

#### Crash Log

https://paste.ubuntu.com/p/VP9JR8Vfsn/

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft:1.12.2
* Forge:2847
* Dropt:1.16.1
* Pyrotech:1.4.21
* Athenaeum:1.17.4
* Patchouli:1.0-20

**Comment by codetaylor** [comment]
This is the same as issue #12 which currently doesn't have a solution. Some have reported that removing Patchouli solves the problem.
