### ISSUE TITLE
Recipes not showing in JEI

### ISSUE THREAD

**Issue by yourmum21** [codetaylor/pyrotech#285]
#### Issue Description

Recipes outside of crafting in a table, like soaking etc. are not showing in JEI in the current version. I backtracked this to version 1.4.17 of the mod as the last one it works in.

#### What Happens

No recipe for instance when clicking slaked lime for the soaking process. Versions 1.4.18+

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* CraftTweaker: - 
* Dropt: 1.17.0
* Pyrotech: 1.4.18+
* Athenaeum: 1.17.4

**Comment by codetaylor** [comment]
What version of JEI are you using?

**Comment by codetaylor** [comment]
Relevant stack trace:
https://gist.github.com/codetaylor/06834ea8860bad8fc316de0b0c71a27c

**Comment by codetaylor** [comment]
Thanks for the report! Fixed in version `1.4.23`.

**Comment by yourmum21** [comment]
Great, what a fast fix, just tested it and it worked great, sorry that i couldn't answer in time nor list the JEI version from the get go but you have figured that out instantly anyway, props and thanks for the great mod, have a nice day :-)
