### ISSUE TITLE
Rendering screen Crash on crafting crude tools.

### ISSUE THREAD

**Issue by Ryzelf** [codetaylor/pyrotech#289]
https://pastebin.com/RpH9MCs0

No script edits
no configs changed 
default state of mods installed 

* Minecraft: 1.12.2
* Forge: 1.12.2-14.23.5.2852.jar
* CraftTweaker:2-1.12-4.1.20.jar
* JEI 1.12.2-4.15.0.291.jar
* Dropt: dropt-1.12.2-1.17.0.jar
* Pyrotech:1.12.2-1.4.23.jar
* Athenaeum: athenaeum-1.12.2-1.17.4.jar
* HWYLA-1.8.26-B41_1.12.2.jar

**Comment by Ryzelf** [comment]
Looking further into it i think i may be a forge issue with the latest version still worth a look into

**Comment by codetaylor** [comment]
Thanks for the report! This is the same as #12
