### ISSUE TITLE
CraftTweaker cannot remove Camp Fire recipes

### ISSUE THREAD

**Issue by drhaber** [codetaylor/pyrotech#290]
I am attempting to remove the "default" campfire recipes that shipped with the mod with the following script
```
val cFireDefaults = [<pyrotech:mushroom_red_roasted>,<netherex:congealed_magma_cream>,<quark:cooked_frog_leg>,
<foodexpansion:itemcookedbatwing>,<quark:cooked_crab_leg>,<pyrotech:apple_baked>,<pyrotech:egg_roasted>,
<emergingtechnology:algaebarcooked>,<pyrotech:carrot_roasted>,<pyrotech:beetroot_roasted>,<pyrotech:mushroom_brown_roasted>,
<minecraft:cooked_beef>,<minecraft:cooked_chicken>,<minecraft:cooked_mutton>,<minecraft:cooked_porkchop>,<minecraft:cooked_fish>,
<minecraft:cooked_rabbit>,<foodexpansion:itemcookedhorsemeat>,<foodexpansion:itemcookedsquid>,<foodexpansion:itemcookedwolfmeat>] as IIngredient[];
for i, CFD in cFireDefaults{
Campfire.removeRecipes(CFD);
}
```
 with no success (I even attempted each entry as it's own line...)

```
Campfire.removeRecipes(<pyrotech:mushroom_red_roasted>);
Campfire.removeRecipes(<netherex:congealed_magma_cream>);
Campfire.removeRecipes(<quark:cooked_frog_leg>);
ect..,
```
Neither of these attempts have proven successful as the recipes still exist in world and in JEI
![image](https://user-images.githubusercontent.com/56454522/78955075-27dd4e80-7aac-11ea-8277-327cb52da0f3.png)
![image](https://user-images.githubusercontent.com/56454522/78955096-34fa3d80-7aac-11ea-8ca3-cfa9c1cc29bb.png)

EDIT:
my full import list for the given ZS file
```
import crafttweaker.item.IIngredient;
import crafttweaker.item.IItemStack;
import crafttweaker.oredict.IOreDictEntry;
import crafttweaker.mods.IMod;
import crafttweaker.liquid.ILiquidStack;
import moretweaker.railcraft.RollingMachine;
import mods.terrafirmacraft.Heating;
import mods.terrafirmacraft.ItemRegistry;
import mods.pyrotech.Campfire;
import mods.pyrotech.PitKiln;
import mods.pyrotech.Bloomery;
import mods.pyrotech.Chopping;
import mods.pyrotech.GraniteAnvil;
import mods.pyrotech.IroncladAnvil;
import mods.pyrotech.CompactingBin;
import mods.pyrotech.SoakingPot;
```

EDIT EDIT:
[Full mod list](https://pastebin.com/q9T600DE)

**Comment by codetaylor** [comment]
Thanks for the report!

```java
static void removeRecipes(
  IIngredient output // output ingredient to match
);
```
This will only remove recipes added by the mod and *will not* remove recipes inherited from vanilla smelting recipes, ie. baked potato, cooked porkchop, etc.

To remove those recipes, you need to use either

```java
static void blacklistSmeltingRecipes(
  IIngredient[] output // output ingredients to blacklist
);
```

or

```java
static void blacklistAllSmeltingRecipes();
```

I tested with

```java
import mods.pyrotech.Campfire;

Campfire.removeRecipes(<pyrotech:mushroom_red_roasted>);
```

and I can confirm that it is not working as intended.

**Comment by codetaylor** [comment]
Nevermind. It is working as intended.

The only recipe added to the Campfire explicitly is the recipe for the guidebook.

All the other recipes are added to vanilla smelting and inherited by the Campfire.

So you will need to use the blacklist methods instead, or remove the recipes using CrT's furnace stuff: https://docs.blamejared.com/1.12/en/Vanilla/Recipes/Furnace/Recipes_Furnace/

You're welcome to join the discord if you have more questions: http://discord.codetaylor.com

**Comment by drhaber** [comment]
The following substitution was a success TY
`furnace.remove(CFD);`
