### ISSUE TITLE
Patreon effect even if i'm not patreon...

### ISSUE THREAD

**Issue by Komplein** [codetaylor/pyrotech#292]
I have hot head effect, i just turned off this in cfg, so this is just information post....

Not so... Magma cube head still there. Patreon.cfg doesn't work. 

Last Forge + MultiMC launcher

**Comment by codetaylor** [comment]
Thanks for letting me know!

I just decompiled the released version and it looks like it is the wrong version... It still has the hard-coded prototype classes.

I'll get this fixed right away.

**Comment by Komplein** [comment]
THX. Your awesome)
