### ISSUE TITLE
Pyrotech clay bucket crash on Agricraft water tank

### ISSUE THREAD

**Issue by DcNdrew** [codetaylor/pyrotech#294]
#### Issue Description

Pyrotech clay bucket crashes when used on Agricraft water tank.

#### What Happens

Get a fired Pyrotech clay bucket (Ceramics one works). Take some water. Pour it in an Agricraft water tank. Crash.

#### What You Expect to Happen

Not crashing.

#### Crash Log

https://paste.dimdev.org/jikevofame.mccrash

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* CraftTweaker: 1.12-4.1.20
* Dropt: 1.12.2-1.17.0
* Pyrotech: 1.12.2-1.4.23
* Athenaeum: 1.12.2-1.17.4

**Comment by codetaylor** [comment]
Fixed in version `1.4.26` and will be available later today.
