### ISSUE TITLE
More mechanical machines

### ISSUE THREAD

**Issue by Derpercoaster** [codetaylor/pyrotech#298]
I feel like having some sort of more automated machine to dry plant fibers (such as by pressing the water out of them or something) would be a good idea. An automated soaking pot-type machine would be helpful as well. THere's probably more machines that could be automated, but I am not sure what to mention other than what I have already.

**Comment by codetaylor** [comment]
You can dry plant fibers in the stone or brick oven and both can be automated. The soaking pot can also be automated, piping fluid in / out as well as items.

**Comment by codetaylor** [comment]
The design philosophy for this mod does not include a high degree of automation, however the automation you mention is available. Please read through the guidebook and play through the mod.
