### ISSUE TITLE
Bloomery compat

### ISSUE THREAD

**Issue by CactusDuud** [codetaylor/pyrotech#304]
#### Issue Description

When using [JAOPCA Ore Chunks](https://www.curseforge.com/minecraft/mc-mods/aobd-ore-chunks) ores generated by that mod (ore chunks from [JAOPCA](https://www.curseforge.com/minecraft/mc-mods/jaopca)) don't work with the bloomery, with the weird exception of vanilla ores and silver for some odd reason. When looking at the custom ore list to change it myself, I realised the unlocalised names are used to register ores instead of registry names. Unfortunately JAOPCA's unlocalised names are all the same due to its auto-generated nature. Ideally an option to use registry names would be included.

#### What Happens

Bloomery won't accept ore chunks as ores, except gold, iron, and silver.

#### What You Expect to Happen

The ability to smelt other ores too.

#### Script

No ct script, but the auto-generated ore list can be found [here](https://pastebin.com/KwD9BUr7)

#### Crash Log

None

#### Affected Versions

* Minecraft: 1.12
* Forge: forge-14.23.5.2854
* CraftTweaker: n/a
* Dropt:  1.18.0
* Pyrotech:  1.4.27
* Athenaeum:  1.18.0

**Comment by codetaylor** [comment]
> the unlocalised names are used to register ores instead of registry names

Not sure what you mean here. The lang keys are only used to display in tooltips. You could provide your own lang key and reference your own lang file provided with ResourceLoader or you could just write in a name like "Unobtanium Ore" and it would use that.

Pyrotech uses the oredict to generate compat. You can read more about how it works here: https://pyrotech.readthedocs.io/en/latest/orecompat/

**Comment by CactusDuud** [comment]
Ah apologies I totally misread. Even still, I'm unable to use JAOPCA ore chunks in the bloomery, even though I have ores like oreLead that are in the auto-generated list. Should I just add them to the bloomery manually?

**Comment by codetaylor** [comment]
No worries. Ensure that the entries that you want to use are in the `core.compat.Ore-Custom.json` file. That's the one that is read and used by Pyrotech. The `core.compat.Ore-Generated.json` is overwritten on each load with the mod's generated stuff, but it's up to you to move any of that stuff into the custom file.

**Comment by CactusDuud** [comment]
Ahh I see. Thank you so much!
