### ISSUE TITLE
Variable itemstack size output.

### ISSUE THREAD

**Issue by Foreck1** [codetaylor/pyrotech#305]
Stations like the kiln or the soaking pot have support for displaying stacks of items as output i.e. x4 bricks from one clay block, but the actual output is always **1**
![image](https://user-images.githubusercontent.com/47757429/83067610-f3f6c200-a034-11ea-8e14-d15cf2e5f79b.png)

**Comment by Foreck1** [comment]
Could be related with https://github.com/codetaylor/pyrotech/issues/295

**Comment by codetaylor** [comment]
Thanks for the report!

I think this may have been an oversight that led to some undesired behavior. The linked issue looks like a non-trivial feature request and I don't think it's directly related to this.

This should be solved in `1.4.29`
