### ISSUE TITLE
Improve guidebook information on mulched farmland

### ISSUE THREAD

**Issue by codetaylor** [codetaylor/pyrotech#32]
User story:
> My final comment would be that the entry on mulch/mulched farmland isn't clear about the fact that this is temporary. The ending of the entry vaguely hints at "the duration of the mulch" -- it wasn't until I was harvesting my wheat just now that I noticed that the effect had ended, and I was checking the guide to see what information there was on that (worried it might've been a conflict with another mod in my mini-pack).

**Comment by Roonas** [comment]
Speaking of conflicts, Better With Mods makes it so bone meal, rather than instantly grow a crop, will instead be applied to the soil and boost it's growth rate indefinitely*tm. Perhaps there could be a compat with this to either disable it's effect or yours to prevent overlap?

**Comment by codetaylor** [comment]
@Roonas Please make a separate issue for that.
