### ISSUE TITLE
Make blocks use "cutout" rendering for resource pack creators. Your textures will still work fine if they don't have transparency.

### ISSUE THREAD

**Issue by crispytwig** [codetaylor/pyrotech#36]
See title.

**Comment by codetaylor** [comment]
So you would like all blocks to use the `cutout` rendering? Or just the crude drying rack?

**Comment by crispytwig** [comment]
All of them, so each individual block won't need to be requested.

**Comment by codetaylor** [comment]
I am hesitant to make such a blanket change to all the blocks and here's why.

Flagging all the mod's blocks to use `BlockRenderLayer.CUTOUT` would indicate to the engine that the blocks have transparency and need to be depth sorted every frame. This would increase performance overhead and, while the overhead might be negligible in many cases, consider the case where a player decides to use a large number of basic, structural blocks from the mod - let's say the Masonry Bricks for the sake of example. If the player were to place thousands of these blocks, even though each block is essentially a full block, they all have to be depth sorted every frame. As a player, I would expect that building with basic blocks like this would have no more impact on performance than, say, cobblestone or stone.

The performance cost of depth sorting every block from this mod, even if the block doesn't require it, would be experienced by every player - whether or not they actually benefit from it by using a texture pack that would take advantage of it.

> Your textures will still work fine if they don't have transparency.

I think at this point I am more concerned about the performance cost of making this change. The cost / benefit ratio here feels very skewed toward cost. Even if the performance cost is negligible, in a modded environment, that cost still adds up.

**Comment by codetaylor** [comment]
I will not be implementing this due to the performance concerns outlined above.
