### ISSUE TITLE
Make drying racks "hang" items rather than placing them atop like a grill.

### ISSUE THREAD

**Issue by crispytwig** [codetaylor/pyrotech#39]
Before:
https://gyazo.com/5ec62aa91d07de9b5220d81115800799
![image](https://user-images.githubusercontent.com/1240716/60530426-8e2b7a00-9cad-11e9-9e37-a035bfc2be40.png)

After:
https://gyazo.com/9c6c97e5589de6d0a0b7c02ffe37120d
![image](https://user-images.githubusercontent.com/1240716/60530456-9c799600-9cad-11e9-9c6f-5363dd16e203.png)

Pretty nifty, huh?

**Comment by crispytwig** [comment]
Whoops, switch those before and afters around.

**Comment by codetaylor** [comment]
I definitely like the visual style of the hanging items in the rack, however, I see two drawbacks to making this change.

First, items laying on top of the drying rack are more easily identified by their shape. I feel that this is important for players who may have difficulty distinguishing between items of a similar color.

Second, it would look bad with blocks. Blocks would overlap the model and each other, causing z-fighting.

**Comment by Exsolutus** [comment]
Would it be possible to hang items, but lay blocks on top?

**Comment by codetaylor** [comment]
I have decided against implementing this for the reasons outlined above.
