### ISSUE TITLE
Bloomery oredictionary ores etc.

### ISSUE THREAD

**Issue by NightmareTwilight** [codetaylor/pyrotech#51]
Hello, as someone who uses other mods I run into the problem that your recipes use hardcoded items instead of oredictionaried ones, specifically I use Divergent Underground which makes ores drop rocks and an ore item, which is oredictionaried, but I can't progress further as there isn't a way to get the ore blocks without silk touch. I feel like using oredictionaried ores would be more compatible with other mods. Adding more ores that are common (and makes sense) if they can be found would be nice too, but not as pressing. 

Also, would you do similar with your other recipes such as Cobbled Diorite etc in the kiln, as well as add them to 'cobblestone' and 'cobblestoneDiorite' oredictionary so that they may be used interchangeably with other mods items/blocks?

**Comment by codetaylor** [comment]
Regarding the oredict and bloomery recipes, the new ore compat system coming in `1.1.0` should address that.

**Comment by codetaylor** [comment]
I will change the default recipes for the bloomery to use the oredict in the interim.
