### ISSUE TITLE
Can't process ZenScript recipes in sawmill when blade becomes damaged

### ISSUE THREAD

**Issue by Kurtchekov** [codetaylor/pyrotech#52]
#### Issue Description

I've created several recipes in CraftTweaker for processing debarked wood in the sawmill. The recipes show up in JEI just fine and, as long the sawmill blade being used is not damaged, it accepts ingredients, in this case debarked wood, and processes it successfully. Once the blade is damaged, the sawmill won't accept the debarked wood anymore, though it still accepts vanilla wood as usual.

Excerpt from my CT script:

```
val blades_tier0 = <pyrotech:sawmill_blade_stone>;
val blades_tier1 = <pyrotech:sawmill_blade_flint> | <pyrotech:sawmill_blade_bone>;
val blades_tier2 =  <pyrotech:sawmill_blade_iron> | <pyrotech:sawmill_blade_obsidian>;
val blades_tier3 =  <pyrotech:sawmill_blade_diamond>;

StoneSawmill.addRecipe("DebarkedOakIntoPlanks_tier0", <minecraft:planks>, <leatherworks:debarked_log_oak>, 1280, blades_tier0, 8);

StoneSawmill.addRecipe("DebarkedOakIntoPlanks_tier1", <minecraft:planks> * 2, <leatherworks:debarked_log_oak>, 960, blades_tier1, 8);

StoneSawmill.addRecipe("DebarkedOakIntoPlanks_tier2", <minecraft:planks> * 2, <leatherworks:debarked_log_oak>, 640, blades_tier2, 8);

StoneSawmill.addRecipe("DebarkedOakIntoPlanks_tier3", <minecraft:planks> * 3, <leatherworks:debarked_log_oak>, 640, blades_tier3, 8);
```

I have also tried to change the blades to accept any damage (.anyDamage() method), but that also was unfruitful.

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* CraftTweaker: 4.1.19
* Dropt: 1.15.0
* Pyrotech: 1.0.8
* Athenaeum: 1.17.1

**Comment by codetaylor** [comment]
Turns out, not a bug :)

Use `<pyrotech:sawmill_blade_stone:*>` instead and it will work. The `:*` indicates that the `ItemStack` should match any meta value.

**Comment by Kurtchekov** [comment]
Great! Can you then update the information on https://pyrotech.readthedocs.io/en/latest/zs/stonesawmill/ and https://pyrotech.readthedocs.io/en/latest/zs/bricksawmill/ ? I used the examples there to make my scripts

**Comment by codetaylor** [comment]
Sure thing!
