### ISSUE TITLE
Unable to remove liquid Clay recipe from Tinker's Construct's Smeltery

### ISSUE THREAD

**Issue by vini2003** [codetaylor/pyrotech#57]
#### Issue Description

Removing PyroTech Clay melting recipe from Tinker's Construct Smeltery melting does **not** remove said recipe. Issue also happens with Clay alloying recipe.

#### What Happens

Using ModTweaker's `mods.tconstruct.Melting.removeRecipe(ILiquidStack)` to remove `<liquid:clay>` recipes such as [these](https://i.imgur.com/XaPjR10.png) does not remove them (screenshot was taken after using said script to supposedly remove the recipe).

#### Expected behavior:

Tinker's Construct Smeltery does **not** keep the recipes seen in the screenshot.

#### Script

`mods.tconstruct.Melting.removeRecipe(<liquid:clay>);`

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* CraftTweaker: 4.1.19
* Dropt: 1.15.0
* Pyrotech: 1.0.8
* Athenaeum: 1.17.1

**Comment by codetaylor** [comment]
This is a TiC issue.

I don't explicitly add anything to TiC and TiC doesn't know about the Pyrotech crucible's melting recipes.

**Comment by vini2003** [comment]
My bad - I'd never noticed liquid Clay was a default thing in Tinker's Construct, so I thought it had something to do with PyroTech.

**Comment by codetaylor** [comment]
No worries :)

**Comment by codetaylor** [comment]
I'm reopening this because I believe it is some kind of conflict and warrants investigation.

**Comment by codetaylor** [comment]
The fluid Liquid Clay `clay` has been renamed to `liquid_clay` to prevent conflict with TiC's Molten Clay `clay`.

Clay?
