### ISSUE TITLE
Advancement "simply slabs" does not check metadata

### ISSUE THREAD

**Issue by Snownee** [codetaylor/pyrotech#58]
#### Issue Description

https://github.com/codetaylor/pyrotech/blob/master/src/main/resources/assets/pyrotech/advancements/stone_slab.json#L22

**Comment by codetaylor** [comment]
What happens? What do you expect to happen?

**Comment by Snownee** [comment]
Pickup cobblestone slab can grant this advancement

**Comment by codetaylor** [comment]
Ah, ok.

Thanks! :)
