### ISSUE TITLE
JEI not showing tab for refractory sawmill anymore

### ISSUE THREAD

**Issue by Kurtchekov** [codetaylor/pyrotech#60]
#### Issue Description

After updating the mod to version 1.0.9, JEI won't show recipes for refractory sawmill anymore, though the machine still processes the recipes it's supposed to. Stone sawmill page still shows up just fine.

#### Affected Versions

* Minecraft: 1.12
* Forge: 14.23.5.2838
* CraftTweaker: 4.1.19
* Dropt: 1.15.0
* Pyrotech: 1.0.9
* Athenaeum: 1.17.1

**Comment by codetaylor** [comment]
From the changelog:
```
* NOTE: Remember to refresh (delete and re-run the game) 
your `Custom` ore dict config file or add the changes manually, 
changes will only appear in the `Generated` file.
```

Have you tried making sure that the `.core.OreDict-Custom.json` is up to date with the `.core.OreDict-Generated.json` file?

The generated file will always contain the mod's default values and the custom file is copied from the generated file only if it doesn't already exist. That means you can edit the custom file and your changes won't be overwritten, but it also means that the mod won't update the custom file with any new default values.

**Comment by codetaylor** [comment]
Nevermind, please disregard my previous comment. I misread the problem.
