### ISSUE TITLE
EDX Multipart prevents right-clicking

### ISSUE THREAD

**Issue by WenXin20** [codetaylor/pyrotech#61]
#### Description

- EDX Multipart has a bug overrides right-clicking.
- For example, holding a slab while right-clicking a door will place the slab first instead of opening the door.
- For this mod, it prevents any interaction with blocks that require a right-click, such as right-clicking a block into a pit kiln. It will instead place the slab above the kiln.
- EDX Multipart hasn't updated in a while, so maybe something can be done here?

#### What Happens

1. Install EDX Multipart
2. Craft the Pit Kiln
3. Craft the cobblestone slab
4. Try to place onto the Pit Kiln
5. Slab is placed above it instead

#### What You Expect to Happen

I expected to be able to place the slab into the Pit Kiln and other blocks.

#### Affected Versions

* Minecraft: v1.12.2
* Forge: v14.23.5.2838
* CraftTweaker: v4.1.19
* Dropt: v1.15.0
* Pyrotech: v1.0.8
* Athenaeum: v1.17.1
* [EDX Multipart](https://minecraft.curseforge.com/projects/edx-multipart): v1.1.1

**Comment by codetaylor** [comment]
I'm unable to find the source for EDX and, therefore, unable to determine what is conflicting.

**Comment by WenXin20** [comment]
Here's a mod link, but it doesn't look like the source code is public.
https://minecraft.curseforge.com/projects/edx-multipart

**Comment by codetaylor** [comment]
Indeed. Without source, though, there isn't even a place to start.
