### ISSUE TITLE
Having an open rock bag suppresses pick-up noises of other items

### ISSUE THREAD

**Issue by duely** [codetaylor/pyrotech#62]
I'm not sure what else I can add...

Pyrotech: 1.12.2-1.0.9

**Comment by codetaylor** [comment]
Yeah... I've actually known about this one since pre-alpha. I've been procrastinating on it tbh, hoping nobody would notice.

Thank you for the report though. :)

**Comment by duely** [comment]
Hah! I have to say, this is one of the things that I noticed immediately as being "off" but couldn't quite place *why* it was wrong. It took me a while to realise that I kept checking around me going "But I don't remember hearing me pick that up". I'm really, really glad it's fixed! Thank you so much.

I'm still procrastinating issues in Arcane Archives... and Roots... and both are close to release.
