### ISSUE TITLE
Add ZenScript support for items the campfire accepts as logs

### ISSUE THREAD

**Issue by Exsolutus** [codetaylor/pyrotech#63]
It is wonderful that the Campfire already supports logWood oredict entries for fuel! However, I would like to add new items (and perhaps remove items?) through ZenScript. The Campfire should then use the new items as fuel and render them in the block.

Example use case: Split logs from PrimalCore

**Comment by Exsolutus** [comment]
I am unable to get the ZenScript methods working. Though the script does not error, the campfire isn't accepting the items. Here's what I've tried:

import mods.pyrotech.Campfire

Campfire.whitelistFuel(<minecraft:coal_block>);
Campfire.whitelistFuel(<primal:logs_split_oak>);

**Comment by codetaylor** [comment]
@Exsolutus please create a new issue.

**Comment by codetaylor** [comment]
@Exsolutus I made a new issue #121
