### ISSUE TITLE
Special stone recipes breaking in latest build

### ISSUE THREAD

**Issue by Roonas** [codetaylor/pyrotech#64]
[As shown here.](https://cdn.discordapp.com/attachments/400504502551052288/591744461222969345/unknown.png) Includes granite, andesite, diorite, and limestone.
* Minecraft: 1.12
* Forge: 14.23.5.2837
* Dropt: 1.15.0 
* Pyrotech: 1.0.8
* Athenaeum: 1.17.1

**Comment by codetaylor** [comment]
From the changelog:
```
* NOTE: Remember to refresh (delete and re-run the game) 
your `Custom` ore dict config file or add the changes manually, 
changes will only appear in the `Generated` file.
```

Have you tried making sure that the `.core.OreDict-Custom.json` is up to date with the `.core.OreDict-Generated.json` file?

The generated file will always contain the mod's default values and the custom file is copied from the generated file only if it doesn't already exist. That means you can edit the custom file and your changes won't be overwritten, but it also means that the mod won't update the custom file with any new default values.

**Comment by Roonas** [comment]
Deleting the config for the 'custom' ore dict files unfortunately failed to propagate any sort of change, so I will be doing int manually for now.

**Comment by codetaylor** [comment]
Try deleting both the custom and generated and see if they both generate.
