### ISSUE TITLE
Improper mushroom conversion.

### ISSUE THREAD

**Issue by Roonas** [codetaylor/pyrotech#65]
#### Issue Description
Brown mushrooms turn into cooked red mushrooms when made in the stone food whatsit after they finish cooking.

#### What You Expect to Happen
*Brown* cooked mushrooms.
#### Affected Versions
Minecraft: 1.12
Forge: 14.23.5.2837
Dropt: 1.15.0
Pyrotech: 1.0.8
Athenaeum: 1.17.1

**Comment by codetaylor** [comment]
Unable to reproduce.

Tested using Pyrotech `1.1.0` with Stone Oven and `minecraft:brown_mushroom` produces `pyrotech:mushroom_brown_roasted`.

**Comment by Roonas** [comment]
When 1.1.0+ is stable (actually able to load) I'll attempt to verify again.

**Comment by codetaylor** [comment]
@Roonas Have you had time to test this?
