### ISSUE TITLE
Support speed changes for crude methods

### ISSUE THREAD

**Issue by BillboardEric** [codetaylor/pyrotech#70]
I noticed you are able to modify the speed of stone and brick machines with things like D:INHERITED_X_RECIPE_DURATION_MODIFIER=X.X

Would be nice to have a similar option, if not a straight speed change option, for all the crude methods like pit kiln and even soaking pot.

**Comment by codetaylor** [comment]
Like a modifier that would be applied across all the recipes for a device?

So, something like `BASE_DURATION_MODIFIER=0.5` would cut the duration of all recipes for that device in half.

**Comment by BillboardEric** [comment]
An option for a speed modifier of pit/refractory burning would be nice too.
