### ISSUE TITLE
Removing Crude Drying Rack recipe not working

### ISSUE THREAD

**Issue by al132mc** [codetaylor/pyrotech#73]
#### Issue Description

When I try to remove a default recipe from the Crude Drying Rack and use my own instead I am unable to do so.

#### What Happens
When I try to remove a default recipe from the Crude Drying Rack (for plant fibers -> dried plant fibers) it does not work and the default recipe seems to take priority over my new recipe

#### What You Expect to Happen
When I try to remove a recipe from the Crude Drying Rack I expect it to work so that I can use my own recipe instead

#### Script
[script](https://pastebin.com/raw/DGEJWex0)
[Image](https://imgur.com/a/AGsIBtu)

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* CraftTweaker: 1.12.2-4.1.19
* Dropt: N/A
* Pyrotech: 1.12.2-1.1.13
* Athenaeum: 1.12.2-1.17.1

**Comment by codetaylor** [comment]
Thanks for the report!

**Comment by al132mc** [comment]
Fixed the image link

**Comment by codetaylor** [comment]
There was an error in the code. It's been fixed for the next build.

**Comment by al132mc** [comment]
Thank you for the quick response
