### ISSUE TITLE
Snow can fall on drying racks. Fence can connect to drying racks

### ISSUE THREAD

**Issue by Snownee** [codetaylor/pyrotech#76]
#### Issue Description

Snow can fall on drying racks. Fence can connect to drying racks

![image](https://user-images.githubusercontent.com/16059084/60006298-b65e1c00-96a2-11e9-9a3f-1429fdb1932c.png)

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 2838
* Dropt: 1.14.0
* Pyrotech: 1.0.7
* Athenaeum: 1.17.1

**Comment by codetaylor** [comment]
Thank you for the report! :)
