### ISSUE TITLE
New chopping block recipe bug ?

### ISSUE THREAD

**Issue by LokyLive** [codetaylor/pyrotech#77]
I just want to notify that the cude axe added to the chopping block recipe is consummed when you craft it.

version       Pyrotech 1.1.4
                   forge : 2838

**Comment by ticviking** [comment]
I'm seeing the same issue on the latest

**Comment by codetaylor** [comment]
Thank you for the report!

The recipe requires an entire undamaged Crude Axe and is currently the intended behavior.
