### ISSUE TITLE
Add config options to change ore capacity for Bloomery & Wither Forge

### ISSUE THREAD

**Issue by Frostnox** [codetaylor/pyrotech#79]

**Comment by CrimsonTyphon** [comment]
Maybe make the wither forge hold 2/4 ores to make it a upgrade to the regular bloomery, and not just the ability to bloom(?) obsidian.

**Comment by codetaylor** [comment]
The Wither Forge will currently process up to 3 ores at once.

**Comment by codetaylor** [comment]
Implemented in 1.4.0
