### ISSUE TITLE
Cutting block recipe change

### ISSUE THREAD

**Issue by CrimsonTyphon** [codetaylor/pyrotech#81]
Instead of using a crude axe and using it up you should use any item that extends ItemAxe decreasing its durability. If you still want to require a full crude axe you could make it need 33 points of durability (durability starts on 0, not 1), just make sure that the axe has that when crafting.

**Comment by codetaylor** [comment]
Something like this has already been implemented in the next version, `1.2.0`

**Comment by codetaylor** [comment]
![2019-06-25_10-26-52](https://user-images.githubusercontent.com/1240716/60280497-e3374c80-98b7-11e9-9343-c6de9731486d.gif)

**Comment by NightmareTwilight** [comment]
Ah, nice!
