### ISSUE TITLE
Missing smelting recipies for unfired items

### ISSUE THREAD

**Issue by NightmareTwilight** [codetaylor/pyrotech#82]
Unfired items can't be fired in a regular furnace, or anything that uses furnace recipes.

**Comment by codetaylor** [comment]
When you submit a bug, please use the issue template that is provided.

Please explain further.

What happens?
What do you expect to happen?

**Comment by codetaylor** [comment]
I think I understand now.

Am I correct that you'd like to see vanilla furnace recipes for the unfired clay bucket?

**Comment by NightmareTwilight** [comment]
Ah, yes.  Sorry for not providing more info, I was busy and just wanted to post it. However, it is not just unfired clay bucket that I'd like to see, but all the unfired items, though personally, I find the bricks to be the most important of them all.

**Comment by NightmareTwilight** [comment]
In the latest version (1.2.1) it shows the recipes in JEI but they don't work (in the furnace), is it already being added to 1.3, or is this a bug?

**Comment by codetaylor** [comment]
It's an issue. Check out #97 for more info.
