### ISSUE TITLE
Patchouli Unlocking

### ISSUE THREAD

**Issue by DrDarkfire** [codetaylor/pyrotech#86]
Would it be possible to have a config option where the patchouli guide doesn't require the advancements? I'm making a pack where I'm writing 100% my own advancements, and as a result the book is permanently locked behind advancements that don't exist.

**Comment by codetaylor** [comment]
Patchouli has an option in its config:
```
# Set this to true to disable advancement locking and make all entries visible at all times
# Config Flag: advancements_disabled
B:"Disable Advancement Locking"=false
```
As far as I know, there isn't a way to do this per mod.
