### ISSUE TITLE
Logs cannot go into Thermal Expansion Sawmill

### ISSUE THREAD

**Issue by Drakoflame** [codetaylor/pyrotech#91]
#### Issue Description

Thermal Expansion machines do not have a recipe to produce planks in JEI.

#### What Happens

I can't put logs into the Sawmill in Thermal Expansion. I tried shift clicking and nothing happens. I have Quark installed, and it has (I'm setting up a personal modpack with friends, we're nowhere near this point but I'd like to fix it before it does become an issue).

https://youtu.be/RIaZXQyQhEQ
this is a 'video' I took of me attempting to put the logs into a sawmill. I don't know if this helps any.

#### What You Expect to Happen

I expected the logs to go into the slot to be able to be used.

#### Script

None.

#### Crash Log

None.

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft: 1.12.2
* Forge: 1.12.2-14.23.5.2838
* CraftTweaker: None
* Dropt: 1.12.2-1.15.0
* Pyrotech: 1.1.7
* Athenaeum: 1.17.2
Thermal Expansion (and required mod) versions:
* ThermalExpansion-1.12.2-5.5.4.43
* CodeChicken Lib 1.12.2-3.2.2.353
* ThermalFoundation-1.12.2-2.6.3.27
* CoFHCore-1.12.2-4.6.3.27
* RedstoneFlux-1.12-2.1.0.6
* CoFHWorld-1.12.2-1.3.1.7

**Comment by codetaylor** [comment]
I can confirm that this is fixed in the next feature release, Pyrotech `1.2.0`, which should be out very soon.

![image](https://user-images.githubusercontent.com/1240716/60391677-c4e47300-9aa8-11e9-95d0-beff8018a292.png)

**Comment by Drakoflame** [comment]
Ah! Alright! Good to know, thanks for the quick reply a well :D
