### ISSUE TITLE
Chopping Block Not Working

### ISSUE THREAD

**Issue by joegman** [codetaylor/pyrotech#93]
#### Issue Description

Not sure if this is intended behaviour but it seems like the chopping block isn't working and no recipes are showing up in JEI

#### What Happens

Right clicking with a log on the chopping block does nothing

#### What You Expect to Happen

The Log appears on the chopping block and is choppable

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* Pyrotech: 1.2.0

**Comment by codetaylor** [comment]
The first time Pyrotech loads, it generates some content based on the other mods you have installed, but it doesn't actually load that content until the game is completely reloaded.

Please try completely reloading the game and see if the Chopping Block works then.

**Comment by mr-V01d** [comment]
Anyone encoring same issue: delete pyrotech config and restart minecraft.

If i understood correctly, some mod that change wood to planks receipt(NoTreePunching, ...) can remove ability to place wood on chopping block.
