### ISSUE TITLE
Config files prefixed with `.` don't import into the Twitch app properly

### ISSUE THREAD

**Issue by ThatGravyboat** [codetaylor/pyrotech#96]
Can you add a config option for pack devs to turn off the generation of recipes on first time load and make it so that it pulls all the recipes from a config file so that the player playing a pack doesnt have to restart the pack after loading it up the first time. Im requesting this because some of the testers for my pack are complaining about having to wait longer bc they have to restart the pack just for the recipes to work.

**Comment by codetaylor** [comment]
> [...] make it so that it pulls all the recipes from a config file [...]

It already does this. The first time the mod is loaded, it looks for the config files. If they don't exist, they are generated in the mod's config folder. Those generated files in the are intended to be manipulated and distributed by the pack-maker, just like any other config files. If these config files are distributed with the pack, players will already have the files and the recipes and content will be generated every time they load.

Any json file in the mod's config folder with the word `Generated` in it will be overwritten every time the game loads. These files should not be modified and only serve as a reflection of the default or mod generated data.

Any json file in the mod's config folder with the word `Custom` in it will be loaded and used by the mod on every load. These are the files that should be modified.

If a `Custom` file is missing, it is created by copying the `Generated` file during load.

**Comment by ThatGravyboat** [comment]
So it kind of a twitch app problem where it doesn't take any of the configs that started with a `.` so it didn't transfer the config files 

- .core.cfg 
- .core.compat.Ore-Custom.json 
- .core.compat.Ore-Generated.json 
- .core.compat.Wood-Custom.json 
- .core.OreDict-Custom.json 
- .core.OreDict-Generated.json 
- .modules.cfg 
- .patreon.cfg 

 Also I tested this multiple times and it happens every time also it happened to the 3 of my testers so I do not know if I need to report this to twitchapp team or you'll have to change the config files from starting with a `.` to nothing. Also thanks for making this mod its a huge part of the beginning game of my modpack.

**Comment by codetaylor** [comment]
Hmm...

I'm not able to reproduce this. This is what I tried:

1. Make a modpack with Pyrotech
2. Generate configs
3. Export modpack; double-checked to ensure that the `.` files were selected for export which they were by default
![TwitchUI_2019-07-03_10-14-02](https://user-images.githubusercontent.com/1240716/60611740-df09a400-9d7b-11e9-9a2a-30af035e22ba.png)
4. Open resulting .zip file and double-check that the `.` files were present
![image](https://user-images.githubusercontent.com/1240716/60611786-03658080-9d7c-11e9-87b8-39f09f872e2c.png)

**Comment by codetaylor** [comment]
...and here we have it:

![image](https://user-images.githubusercontent.com/1240716/60612020-98687980-9d7c-11e9-93db-3d71bf83a4ff.png)

This is the result of the config folder after import. All the files with the leading `.` are missing.

Yeah, I see this as a big issue and you can report it to twitch/curse/amazon/whatever if you want, but I think it's also a good idea if I correct this on my end simply by removing the `.`.

**Comment by codetaylor** [comment]
Fixed in 1.12.2-1.2.2 and will be available later today.

The leading `.` has been removed from config files. If you want to preserve your existing config files, simply remove the leading `.` before launching.
