### ISSUE TITLE
Add config options to disable durability loss for various things.

### ISSUE THREAD

**Issue by AnotherVagabond** [codetaylor/pyrotech#98]
Mostly talking about durability loss when using gears in machines, since that's the specific issue one of the discord people was citing as why they aren't interested in the mod, but I suppose it would be good for all sorts of things (like hammer crafting and so on, or even crafting tables and anvils themselves). This way people who don't want to have to constantly replace parts of their crafting machines don't have to worry about that.

**Comment by codetaylor** [comment]
I agree. I think some of the things mentioned might already have a way to configure them to not wear out, but I don't fully remember.

I think these are the only things that wear out:

* hammers
* sawblades
* cogs
* worktables
* chopping block
* anvil

If I missed something, leave a comment.

**Comment by codetaylor** [comment]
* ~hammers~
Hammers can already be configured to not take damage in the `core.cfg`, so nothing done there
* sawblades
Sawblade items can now be added to a list of indestructible sawblades
* cogs
Cog items can now be added to a list of indestructible cogs
* ~worktables~
Worktables can already be configured to not use durability, so nothing done there
* chopping block
Chopping block can now be set to not use durability
* anvil
Both anvils can now be set to not use durability
